### ISSUE TITLE
[Bug]: Lowest returns a single result in the WebApi - this should be an array 

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#103]
### What happened?

[Bug]: Lowest returns a single result in the WebApi - this should be an array since multiple regions and times may match the lowest emissions.  The decision of which region/time to use should sit with the consumer of the information.

For example, the lowest emissions may be `now` and `1 hour from now` and the application to decide whether to use the soonest for expedience or delay an hour for better use of time.

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dylHall** [comment]
Happy to pick this up

**Comment by vaughanknight** [comment]
Resolved in #104
