### ISSUE TITLE
[Release]: Formally releasing 1.0 - get this reviewed by working group and merge into main

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#111]
### What happened?

Tracking officially creating Release 1.0

Steps:
- PR into main created and ready for review
- @Willmish to submit to working group on regular meeting (next is on the 28th of Sept)
- 2 weeks open to review
- Merge to main branch

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Willmish** [comment]
Closed in #113
