### ISSUE TITLE
[Feature Contribution]: Suggested improvements to documentation

### ISSUE THREAD

**Issue by hayasri** [Green-Software-Foundation/carbon-aware-sdk#116]
### What happened?

As part of documentation, there is value in expressing that carbon aware software should also take demand side into consideration. 

"At times of higher demand, like 6-8pm or in the afternoons on a very hot day, the grid is more strained and often more dirty," 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by Willmish** [comment]
Hi @hayasri , thanks for creating the issue. Are you planning on adding a PR with these changes?
