### ISSUE TITLE
All architecture decisions should have an ADR

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#13]
All architecture decisions should have an architecture decision record.  This is so we can track the rationale behind why we made decisions, but also give us a way to discuss and finalise on proposed architecture decisions.

**Comment by navveenb** [comment]
Hi Vaughan, Can you please share the technical spec and current architecture. Is this is currently being prepared, I would like to contribute towards it.

**Comment by vaughanknight** [comment]
Hi Naaveen - Apologies!  I only just saw this.  Getting used to checking all the threads now we have people keen to contribute.  I'm going to start doing lots of overviews, and some videos as we slowly update all the documentation.

At the moment everything is in the 'dev' branch, and the src/dotnet being the code currently.  I'll share some information relating to the current web api (it's a first 0.1 alpha cut) to give you an idea of where the project is heading.

**Comment by vaughanknight** [comment]
Also - Be sure to check in on the Slack channel https://greensoftwarefdn.slack.com/archives/C02JRAV4QEP

**Comment by navveenb** [comment]
Thanks @vaughanknight for the details.

**Comment by vaughanknight** [comment]
Closing out as this can move to documentation
