### ISSUE TITLE
[Bug]: Cannot register when org is using a self signed certificate.

### ISSUE THREAD

**Issue by tmcclell** [Green-Software-Foundation/carbon-aware-sdk#138]
### Contact Details

tmcclell@microsoft.com

### What happened?

Walking through registering for a Watttime account via the SDK and was met with an error related to the person using a self signed certificate. Unable to register via python.

### client

WebAPI (Default)

### Relevant log output

```shell
I can recreate the exact working if this is needed.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Willmish** [comment]
Hi @tmcclell , thanks for raising this!

Would it be possible for you to share the logs for it/the exact steps? Are you following this: https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/samples/watttime-registration/readme.md ?

CCing in, @danuw in case you encountered this before.

**Comment by Willmish** [comment]
@tmcclell Re-surfacing this - any updates on this, or where you able to resolve the issue?

**Comment by danuw** [comment]
I am not sure I have done quite a few registrations via python and functions apps (csharp) and not had this issue.

Would it be possible to get some steps to try and reproduce please?
