### ISSUE TITLE
[Bug]: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by ng-druid** [Green-Software-Foundation/carbon-aware-sdk#139]
### Contact Details

todd@rollthecloud.com

### What happened?

When attempting to use the hosted REST API directly in the browser CORS error occurs due to lack of appropriate headers. It would be nice to add CORS so that this API can be hit directly without requiring a wrapper API.

<img width="1440" alt="Screen Shot 2022-10-02 at 6 04 40 PM" src="https://user-images.githubusercontent.com/73197190/193478421-8f07b177-578d-4c08-b287-d1258ea8d435.png">

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Willmish** [comment]
@vaughanknight will look at it, thanks!

**Comment by danuw** [comment]
Hi, sorry for the delay. This should now work 
[link to test](https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fcarbon-aware-api.azurewebsites.net%2Femissions%2Fbylocations%2Fbest%3Flocation%3Duksouth%26time%3D2022-03-01T15%253A30%253A00Z%26toTime%3D2022-03-01T18%253A30%253A00Z&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote)

Please retest and let us know if you get anymore issues.

Thanks
Dan
