### ISSUE TITLE
[Bug]: Some azure regions return an error

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#145]
### What happened?

When testing for different Azure Regions, the WebApi returns an error message. Some regions get a 500 and some other get a 400.

https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/src/CarbonAware.LocationSources/CarbonAware.LocationSources.Azure/src/azure-regions.json

I first thought the location were incorrect. So I generated a new data source by running the following Azure Cli command:
`az account list-locations --query '[].{RegionName:name,Longitude:metadata.longitude,Latitude:metadata.latitude}' > azure-regions.json`

There were some new regions. Mostly, I noticed some came back null as the current data source seems to contain, those are the 500.
It is possible to remove the null geo point by using
`az account list-locations --query '[?metadata.latitude != null].{RegionName:name,Longitude:metadata.longitude,Latitude:metadata.latitude}' > azure-regions.json`

When looking at the WattTime documentation, the map coverage shows that some regions (and therefore some coordinates) are not supported (see https://www.watttime.org/explorer/#1.82/29.3/-15.33). Those are the 400 such as Brazil.

What should the API return in that case? Is 400 as not found OK? In that case, should we remove the regions with null values? The API would then return `"Unknown region: Region name 'uae' not found"` which seems to make more sense.

## So In summary:

Run:
```bash
curl -X 'GET' \
  'http://localhost:5073/emissions/bylocations/best?location=uae&time=2022-03-01T15%3A30%3A00Z&toTime=2022-03-01T18%3A30%3A00Z' \
  -H 'accept: application/json'
```

Expected: enter an official Azure region name, and get a sucessful response or a comprehensive error message

Actual: 
```json
{
  "title": "InternalServerError",
  "status": 500,
  "traceId": "00-baf00c893d36060ce5183d5632889e96-69a5e57941e9dcbe-00",
  "errors": {}
}
```

OR

Run:
```bash
curl -X 'GET' \
  'https://carbon-aware-api.azurewebsites.net/emissions/bylocations/best?location=brazilsouth&time=2022-03-01T15%3A30%3A00Z&toTime=2022-03-01T18%3A30%3A00Z' \
  -H 'accept: application/json'
```

and Get:
```json
{
  "title": "WattTimeClientHttpException",
  "status": 404,
  "detail": "Error requesting ba-from-loc?latitude=-23.55&longitude=-46.633",
  "traceId": "00-c165339f320432e95e510b7f940342d5-a8bad81525278063-00",
  "errors": {}
}
```

## Proposal:
1. Clean up azure-regions.json of null values to get unknown region
2. Wrap Watttime 404 into location not supported

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bderusha** [comment]
@danuw We have a fix for this that wasn't quite ready in time for the 1.0 release, but it replaces the Azure location source with a more generic "named location -> geocoordinates" mapper and cleans up the errant null values in the azure json file.
