### ISSUE TITLE
[Bug]: Locations are not working

### ISSUE THREAD

**Issue by iwt-nduesing** [Green-Software-Foundation/carbon-aware-sdk#152]
### What happened?

Hi, I tried a lot of locations like `de`, `Germany`, `Hamburg`, `Deutschland`, non worked, so I thought you maybe use AWS regions [as they are also listed in this repo](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/eca59006c1d27e19a6be900d42f1ab60bea634ea/src/data/data-sources/test-data-aws-emissions.json). But they don't work either. I found the sentence "Location is a required parameter and is an array of the names of the data region for the configured Cloud provider." [in the documentation](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/0d123b1c701eaf25ebb4f02a5667b6c64ae94fa2/docs/carbon-aware-webapi.md), but there is no option in swagger to configure a Cloud Provider, and `us-east-1` or `eu-west-1` fail with "Unknown region". Can you please provide an endpoint with available locations or a list somewhere?

### client

WebAPI (Default)

### Relevant log output

```shell
{
  "title": "ArgumentException",
  "status": 400,
  "detail": "Unknown region: Region name 'eu-west-1' not found",
  "traceId": "00-1028f533fed8edeed14129a4c13055a1-49b50516233ee04a-00",
  "errors": {}
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esgraham** [comment]
The current release supports Azure regions, and the names can be found here:  https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/src/CarbonAware.LocationSources/CarbonAware.LocationSources.Azure/src/azure-regions.json

We have proposed a solution where you can add additional locations and custom names:  #157
