### ISSUE TITLE
[Bug]: CLI does not respect Logging configuration

### ISSUE THREAD

**Issue by woodcoder** [Green-Software-Foundation/carbon-aware-sdk#168]
### Contact Details

andy@bitshaper.co.uk

### What happened?

The CLI currently always has Console debug output enabled, making parsing the JSON difficult as it is printed to the console twice, once as expected, and once in a LogCritical line:

https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/d623ea19971324b553dee35d33a0df90d2aa25a7/src/CarbonAware.CLI/src/CarbonAwareCLI.cs#L92-L93

Configuring the `LogLevel` in the `appsettings.json` to `"None"` is ignored and does not work.

I believe this is because the `services.AddLogging` call here:
https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/d623ea19971324b553dee35d33a0df90d2aa25a7/src/CarbonAware.CLI/src/Program.cs#L30

Should read something more like:
```
        services.AddLogging(configure => configure
            .AddConfiguration(config.GetSection("Logging"))
            .AddConsole()
        );
```

### client

CLI

### Relevant log output

```shell
$ dotnet run -l eastus
info: CarbonAware.DataSources.Json.JsonDataSource[0]
      JSON data source getting carbon intensity for locations {"locationType":2,"latitude":null,"longitude":null,"cloudProvider":null,"regionName":"eastus","name":"eastus","displayName":"eastus"} for period 10/25/2022 09:27:01 +01:00 to 10/25/2022 09:27:01 +01:00.
info: CarbonAware.DataSources.Json.JsonDataSource[0]
      Reading Json data from carbon-aware-sdk/src/CarbonAware.CLI/src/bin/Debug/net6.0/data-sources/json/test-data-azure-emissions.json
{
  "emissionsData": [
    {
      "Location": "eastus",
      "Time": "2022-10-25T04:45:11+00:00",
      "Rating": 53.0,
      "Duration": "08:00:00"
    }
  ]
}
crit: CarbonAware.CLI.CarbonAwareCLI[0]
      {
        "emissionsData": [
          {
            "Location": "eastus",
            "Time": "2022-10-25T04:45:11+00:00",
            "Rating": 53.0,
            "Duration": "08:00:00"
          }
        ]
      }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esgraham** [comment]
This issue was addressed and fixed in pull request:  Carbon Aware CLI redesign #158
