### ISSUE TITLE
[Feature Contribution]: Create a C# API Contract that exists as a consumer layer for Forecast and Marginal Rates

### ISSUE THREAD

**Issue by esgraham** [Green-Software-Foundation/carbon-aware-sdk#171]
### What happened?

As a developer of a carbon-aware application, I want to consume the Forecast and Average Carbon Intensity api as c# library so that I can run the SDK within a single application.

## Context

Currently the SDK can only be used as a runtime (CLI/Web API) and we need to run the SDK as C# client library. Propose adding a new dotnet project that lives above the Aggregator to handle access to the core business logic and configuration management.

This Features Implements the [SDK as a C# Client Library ADR](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0009-sdk-as-a-c%23-client-library.md)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by vaughanknight** [comment]
@esgraham - Is the title meant to be "marginal rates"?

**Comment by vaughanknight** [comment]
Realised I could update it myself, pretty sure it's meant to be rates, if not please change it back and reprimand me in kind.
