### ISSUE TITLE
[Bug]: WattTime passwords with non-ASCII characters fail

### ISSUE THREAD

**Issue by woodcoder** [Green-Software-Foundation/carbon-aware-sdk#181]
### Contact Details

andy@bitshaper.co.uk

### What happened?

My autogenerated WattTime password contains a £ (GBP/pound sterling) character.

When this is encoded by the `SetBasicAuthenticationHeader()` it is corrupted by the `Encoding.ASCII`:

https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/v1.0.0/src/CarbonAware.Tools/CarbonAware.Tools.WattTimeClient/src/WattTimeClient.cs#L249-L253

This caused a valid password that could successfully be used directly with curl (or even directly in a web browser):
```
curl https://api2.watttime.org/v2/login -u 'username:pass£word'
```

To fail with the following response:
```
Login failed for user username.  Response: StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1
```

Changing to use `Encoding.UTF8` fixes this issue.

### client

CLI

### Relevant log output

```shell
info: CarbonAware.Tools.WattTimeClient.WattTimeClient[0]
      Attempting to log in user <username>
info: System.Net.Http.HttpClient.WattTimeClient.LogicalHandler[100]
      Start processing HTTP request GET https://api2.watttime.org/v2/login
info: System.Net.Http.HttpClient.WattTimeClient.ClientHandler[100]
      Sending HTTP request GET https://api2.watttime.org/v2/login
info: System.Net.Http.HttpClient.WattTimeClient.ClientHandler[101]
      Received HTTP response headers after 1046.8211ms - 403
info: System.Net.Http.HttpClient.WattTimeClient.LogicalHandler[101]
      End processing HTTP request after 1053.9582ms - 403
fail: CarbonAware.Tools.WattTimeClient.WattTimeClient[0]
      Login failed for user <username>.  Response: StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
      {
        Date: Mon, 24 Oct 2022 15:33:31 GMT
        Connection: keep-alive
        Server: nginx
        Content-Type: text/html
        Content-Length: 146
      }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vaughanknight** [comment]
Oh wow, so this was your auth issue last week?  Can be easily updated.

**Comment by woodcoder** [comment]
Yes - I think I was unlucky to be allocated that particular password.

Anyway, hopefully a fix will avoid other folk coming across the same problem, thank you!

**Comment by Willmish** [comment]
Bug still present after code changes: https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/src/CarbonAware.DataSources/CarbonAware.DataSources.WattTime/src/Client/WattTimeClient.cs#L251
