### ISSUE TITLE
[Feature Contribution]: Support for permissively licensed annual marginal intensity data

### ISSUE THREAD

**Issue by mrchrisadams** [Green-Software-Foundation/carbon-aware-sdk#189]
Hi there, the org I work for, the Green Web Foundation has been working with the the UNFCCC to get the greenlight for us to publish their annually updated marginal intensity data with a license that allows it to be included in open source software libraries.

We've been able to do this now, and [it's packaged into CO2.js, an OSS library we have created](https://developers.thegreenwebfoundation.org/co2js/overview/) to make it easy to incorporate calculations into software so it can self-report its own emissions. 

We [also have a golang library we're planning to add it to](https://developers.thegreenwebfoundation.org/grid-intensity-cli/overview/), and given that's freely licensed, I think could work as a data source for the Carbon Aware SDK.

This would mean that even if you don't have an API key from providers like Watttime, or can't make outbound API requests, you could start coming up with marginal intensity numbers, to make it possible to create SCI scores (with the caveat that you're using numbers that would update annually, so they wouldn't be suitable for certain use-cases).

I'm not sure, but there may be places where the UNFCCC numbers we were able to republish provide coverage where there isn't info.

Also, when you combined this with IP geolocation software, you could start coming up with very high level estimates for services from providers, based on their geolocated IP address, for cases where you don't have region level info published.

We do this with our own IP-to-carbon-intensity API, and the source code for how do this is public on our own codebase - I'm happy to show how we did it for others to take a similar approach:
https://developers.thegreenwebfoundation.org/api/ip-to-co2/overview/

Anyway, none of our team really know C#, otherwise we'd make a pull request, offering to help do this ourselves.

There's also a few edge cases to iron out, like what fallback figures ought be when data for a given country doesn't exist.

👍🏽?

PS. This initial work was [funded by the RIPE NCC community network fund, on the "carbon aware internet" project](https://www.ripe.net/support/cpf/ripe-ncc-community-projects-fund) - we've put a second bid in to raise some funding to allocate developer time to contribute to this work in 2023, but we won't hear if the funding is approved til later in the year. I'll update if we do tho, as it'll be easier for us to make proper commitments of resources over the next 12 months at that point.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by vaughanknight** [comment]
Super interested in data sources and how we can use them, will definitely review this.  Might take us some time as our backlog is growing but will let you know!
