### ISSUE TITLE
[ADR Review]: Weekly Review of ADRs

### ISSUE THREAD

**Issue by YaSuenag** [Green-Software-Foundation/carbon-aware-sdk#201]
### What happened?

This is to track the review of the following ADRs:

- [ ] CD pipeline for release process [0011-cd-pipeline.md](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0011-cd-pipeline.md)

These ADRs are to be reviewed independently but discussion can be on this thread. If members have discussions via Zoom/Teams/etc outputs from those discussions must be put in this thread as they relate to the reviews.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by Willmish** [comment]
Closed as ADR accepted, as discussed during #258
