### ISSUE TITLE
🎯2022 12 06 - Carbon Aware SDK Agenda

### ISSUE THREAD

**Issue by dohafernandez** [Green-Software-Foundation/carbon-aware-sdk#204]
## Date
2022-12-06 - 8am UTC

## Meeting notices
We are now moving to formal meeting agendas for the weekly call.

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Doha Fernandez | GSF | [dohafernandez](https://github.com/dohafernandez) | 
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
- [x] Discuss Issues
- [x] AOB, Q&A & Adjourn (5mins)

## Issues
- [x] 1.0.1 Release discussion 
- [x] Issue #201 
- [x] #200 update

## Decisions Made
- [ ] January for 1.01 release
- [ ] Agree to review GH packages before they are approved (1 week) #201 
- [ ] Any hackathon spin off projects need to be discussed with Opensource WG

## Action Items
- [ ] @Willmish to set up cadence with Bill from Microsoft in western US time zone. 
- [ ] @vaughanknight to review current PRs
- [ ] @danuw @vaughanknight @Willmish to review GH packages 
- [ ] @danuw to remove hackathon content from the read.me page
- [x] @dohafernandez Create an issue for track tasks for 1.01 release
- [ ] @dohafernandez set up separate call with @vaughanknight & @buhongw7583c  to update [issues and the board](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/180)

**Meeting attended by**
@vaughanknight @Willmish @dohafernandez @FabioTurati-NTT @YaSuenag @buhongw7583c @danuw

**Comment by dohafernandez** [comment]
Attended

**Comment by FabioTurati-NTT** [comment]
Attended

**Comment by buhongw7583c** [comment]
Attended, first time. Hello. :)

**Comment by danuw** [comment]
Attended
