### ISSUE TITLE
[PM]: Release 1.01 🗓

### ISSUE THREAD

**Issue by dohafernandez** [Green-Software-Foundation/carbon-aware-sdk#205]
**What:** Task tasks for 1.01 release

**Why:** Preparing for a January release. We need an organized list of tasks with assignees. 

**Scope of Work**
- [ ] 

**Related Issues:**
- [ ]

**Comment by dohafernandez** [comment]
@vaughanknight @danuw @Willmish Please populate the issue with tasks and some information about the tasks. Then I can create an issue for each separately if needed. 
If an issue already exists then please add it here as well.

**Comment by holanita** [comment]
@vaughanknight @danuw @Willmish when Doha handed over her projects to me, she advised that you guys might need some initial assistance with setting up Github and adding tasks. let me know if you'd like to have a chat on this. I'd be happy to tell you more about how we use Github for PM or just feel free to let me know what questions or thoughts you have.

I understand from Doha's updates that everything is on track for the January release though, but please let me know if that is not the case and we'll be happy to help. thanks!

**Comment by Willmish** [comment]
Moved to #308
