### ISSUE TITLE
🎯2022-12-13 - Carbon Aware SDK Agenda

### ISSUE THREAD

**Issue by dohafernandez** [Green-Software-Foundation/carbon-aware-sdk#206]
## Date
2022-12-13 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
- [x] Discuss Issues
- [x] Electricity Map Support Discussion (Fabio)
- [ ] AOB, Q&A & Adjourn (5mins)

## Issues
- [ ] 
- [ ] 
- [ ] 

## Decisions Made
- [ ] 
- [ ] 
- [ ] 

## Action Items
- [ ] Dan to look at SOGS banner PR and look to merge it with his PR
- [ ] Dan to look at DevOps and helping drive/define (no actual actions yet, maybe speak to it in next meeting?  or the next/next?) 
- [ ] Vaughan to check if Azure has any unused resources
- [ ] Vaughan to ensure PM is added into calls / channels 
- [ ] Vaughan to follow up on ElectricityMap key
- [ ] Add ElectrictyMap Free support to agenda for next week

**Meeting attended by**

**Comment by danuw** [comment]
Attended

**Comment by FabioTurati-NTT** [comment]
Attended
