### ISSUE TITLE
[terminology]: mean marginal vs. average carbon intensity

### ISSUE THREAD

**Issue by buchananwp** [Green-Software-Foundation/carbon-aware-sdk#215]
### Contact Details

wibuchan@microsoft.com

### What happened?

It's not a bug, it's a terminology suggestion. 

emissions/average-carbon-intensity

For this query, the carbon-aware-sdk returns a **mean marginal carbon intensity** 

'average' carbon intensity is an actual data type provided by WattTime and ElectricityMap. Marginal is a _different_ type. Can we be consistent in our terminology? 

### client

WebAPI (Default)

### Relevant log output

```shell
n/a
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vaughanknight** [comment]
Thanks Will!  This is something we're going to be looking at moving forward also (terminology).

**Comment by buchananwp** [comment]
Is this still in-progress?
