### ISSUE TITLE
[Feature Contribution]: Solution to decarbonize your Azure Functions

### ISSUE THREAD

**Issue by georgekosmidis** [Green-Software-Foundation/carbon-aware-sdk#223]
### What happened?

Based on your repo I created a small library that can be used in Azure Functions with a Timer Trigger, to run only withing the optimal window of execution.

I named it Greenhopper and although it still needs a few things (e.g. unit testing), it is already working in production in project - It aggregates report data only within the optimal window.

Please check it here, I would love if more people decide to run their async workloads during greener times: https://github.com/georgekosmidis/Greenhopper

P.S.
It is already a nuget package: https://www.nuget.org/packages/Greenhopper/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by Willmish** [comment]
Hey @georgekosmidis and congrats on releasing your project! Is there a further action you wanted to take on this issue?
Maybe add an example usage of GreenHopper as a sample usage of the CA SDK (similar to how we have this, but instead with an external reference: https://github.com/Green-Software-Foundation/carbon-aware-sdk/tree/dev/samples/azure/azure-function)

What do you think @georgekosmidis @vaughanknight ?
