### ISSUE TITLE
[Bug]: ConsoleApp does not compile

### ISSUE THREAD

**Issue by pritipath** [Green-Software-Foundation/carbon-aware-sdk#229]
### What happened?

The ConsoleApp sample does not compile right out of the box. I would expect it to compile and guide to how to configure

**Relevant log output**

C:\code\carbon-aware-sdk\samples\lib-integration\ConsoleApp> dotnet run
C:\code\carbon-aware-sdk\samples\lib-integration\ConsoleApp\Program.cs(1,7): error CS0246: The type or namespace name '
GSF' could not be found (are you missing a using directive or an assembly reference?) [C:\code\carbon-aware-sdk\samples
\lib-integration\ConsoleApp\ConsoleApp.csproj]
C:\code\carbon-aware-sdk\samples\lib-integration\ConsoleApp\Program.cs(2,7): error CS0246: The type or namespace name '
GSF' could not be found (are you missing a using directive or an assembly reference?) [C:\code\carbon-aware-sdk\samples
\lib-integration\ConsoleApp\ConsoleApp.csproj]
C:\code\carbon-aware-sdk\samples\lib-integration\ConsoleApp\Program.cs(3,7): error CS0246: The type or namespace name '
GSF' could not be found (are you missing a using directive or an assembly reference?) [C:\code\carbon-aware-sdk\samples
\lib-integration\ConsoleApp\ConsoleApp.csproj]

The build failed. Fix the build errors and run again.

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juzuluag** [comment]
@pritipath , should be this close too?

**Comment by pritipath** [comment]
Based on the offline discussion with @juzuluag, the original implementation was by design. The sample console app is never intended to run independently. Before running the app, we need to run the scripts to ensure the packages are created and added to the app. Please see the documentation [here ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/packaging.md#console-app-sample)for more details.
