### ISSUE TITLE
[Bug]: GSF Web API deployment ​/emissions​/forecasts​/current not working

### ISSUE THREAD

**Issue by zyang37** [Green-Software-Foundation/carbon-aware-sdk#233]
### What happened?

Hi, I was trying to use the WebAPI to get the forecast data, but I keep getting an error saying that `ForecastDataSource is not configured`. I think my inputs are correct since it was working before. 

### client

WebAPI (Default)

### Relevant log output

```shell
{'detail': 'ForecastDataSource is not configured',
 'errors': {},
 'status': 400,
 'title': 'ArgumentException',
 'traceId': '00-5f49566f3868bb03c1731c5864876487-01e3196c49b466c6-00'}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Willmish** [comment]
HI @zyang37 , as of #188 `ForecastDataSource` and `EmissionsDataSource`, see https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/GettingStarted.md#configuration-options and https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/configuration.md

**Comment by zyang37** [comment]
Hi, thanks for your reply. I wasn't trying to host it myself. I was using the WebAPI (https://carbon-aware-api.azurewebsites.net/swagger/index.html)

**Comment by Willmish** [comment]
@zyang37 I see, the configs for the hosted API need to be updated in that case. Bear in mind, that the publicly hosted API is intended for development/demo purposes so will be breaking as PRs come through. Reopening this issue until the config gets updated.

**Comment by Willmish** [comment]
@zyang37 should be fixed now, closing.

**Comment by zyang37** [comment]
@Willmish Thank you!
