### ISSUE TITLE
🎯2023-01-03 - Carbon Aware SDK Agenda 

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#234]
## Date
2023-01-03 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
- [x] Discuss Issues

## Discussion 
- [ ] 1.1.0 Release from current dev branch - With CHANGELOG and updates to documentation, plus guide on how to upgrade
- [ ] Review of current PR's over 2022-2023 Holiday period for 1.2.0
- [ ] 

## Action Items
- [x] Dan to look at SOGS banner PR and look to merge it with his PR - Closed out
- [ ] Dan to merge the PR to remove banner 
- [ ] Dan to look at DevOps and helping drive/define (no actual actions yet, maybe speak to it in next meeting?  or the next/next?) 
- [ ] Vaughan to check if Azure has any unused resources
- [ ] Vaughan to ensure PM is added into calls / channels 
- [ ] Vaughan to follow up on ElectricityMap key
- [x] Add ElectrictyMap Free support to agenda for next week (10th January)

**Meeting attended by**

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by vaughanknight** [comment]
Attended

**Comment by danuw** [comment]
Atended

**Comment by Willmish** [comment]
Attended

**Comment by Willmish** [comment]
Closed as meeting notes approved on #235
