### ISSUE TITLE
[Bug]: Multiple locations array does not work for the API

### ISSUE THREAD

**Issue by MartinDawson** [Green-Software-Foundation/carbon-aware-sdk#247]
### What happened?

This API endpoint works:

/emissions/bylocations?location=westus&location=eastus&time=2022-12-16T18%3A47%3A47.196Z&toTime=2023-01-15T18%3A47%3A47.197Z

This API endpoint does not: 

/emissions/bylocations?location=westus,eastus&time=2022-12-16T18%3A59%3A25.994Z&toTime=2023-01-15T18%3A59%3A25.994Z

The latter results in:

{
  "title": "ArgumentException",
  "status": 400,
  "detail": "Unknown Location: 'westus,eastus' not found",
  "traceId": "00-036a49500aeacd844ac19a2310bfcc9e-d2e8bfdfa6a41380-00",
  "errors": {}
}

However when using OpenAPI to generate the SDK, it's putting the params as an string[] like so:

getEmissionsDataForLocationsByTime(location: Array<string>, time?: Date, toTime?: Date, _options?: Configuration): Promise<void | Array<EmissionsData>>;

I believe this is because of the DTO schema:

    /// <summary>String array of named locations</summary>
    /// <example>eastus</example>
    [FromQuery(Name = "location"), SwaggerParameter(Required = true)]
    public override string[]? MultipleLocations { get; set; }
    
So either an string[] of locations should work or the DTO is wrong?

I'm using the typescript generator for this:

openapi-generator-cli generate -i http://localhost:5073/swagger/v1/swagger.json -g typescript -o ./typescript \
    --additional-properties=npmVersion=1.0.0

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juzuluag** [comment]
Hi @MartinDawson , the OpenApi version generated by Swashbuckle framework is:
```json
openapi: 3.0.1
...
```
The query format follows the [query parameters 3.0 spec](https://swagger.io/docs/specification/serialization/), which used the default serialization method. See `Query Parameters` section for more details.

**Comment by juzuluag** [comment]
Tagging @vaughanknight and @gfmatthews, to mention that this **works** as expected.

**Comment by MartinDawson** [comment]
@juzuluag Hmm okay, I'm a bit confused though here then. What's the fix for this issue then? I presume I'm doing something wrong on my side?

**Comment by juzuluag** [comment]
> @juzuluag Hmm okay, I'm a bit confused though here then. What's the fix for this issue then? I presume I'm doing something wrong on my side?

@MartinDawson, there is not fix here. The correct format based on the spec 3.0, is to have the query string as: `..?location=eastus&location=westus&...`
The old (2.0) format is the one that you mentioned.
