### ISSUE TITLE
[Bug]: Consolidate `GettingStarted.md` and `docs/quickstart.md` documentation

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/carbon-aware-sdk#259]
### Contact Details

GitHub/Slack: Willmish

### What happened?

Issues like https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/230 and https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/232 start arising due to the documentation not keeping up to date with the quickly evolving codebase. As addressed in https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/231 , the startup guides are unsynchronised and need to be brought up to date + solidified. 

For example - Client generation is properly explained in [`src/clients/README.md`](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/src/clients/README.md) but is not properly referenced in the `GettingStarted.md` guide.

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pritipath** [comment]
@Willmish @vaughanknight This ticket needs to be closed since the related PR has been merged.
