### ISSUE TITLE
Build out React/Typescript/Node-ish Demo Using the SDK

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#26]
We want to build out a web demo using the SDK.  While we have some ideas on what to do, we're looking for:
* HTML/CSS skills
* React skills
* Typescriptt skills
* Node skills

Please reply here as to what you could provide, and we can start to shape it up!

**Comment by gnomeontherun** [comment]
I've got the above, more Angular than React, but suspect that isn't as important.

**Comment by vaughanknight** [comment]
That's great @gnomeontherun ! ... we could have both :) ... if you are keen I have some ideas of what a demo could be, and we can move it across to the discussions #33

**Comment by juliana-witzke** [comment]
Hey everyone, 
I can definitelly help with HTML/CSS skills. I am more familiar with React, but I'm currently working with typescript so maybe I can help with that as well. I am finishing a (long) course about Node so maybe this can also be an opportunity to put this recent knowledge in practice. Let me know!

**Comment by Everyways** [comment]
Help needed ?
