### ISSUE TITLE
Build out a python demo using the SDK

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#27]
We are looking to build out a good demo in python for the SDK.  Demo would be using the REST endpoint or the CLI, with the python doing [something pythony(TIM)]

[something pythony(TIM)] is yet to be defined.  It could be a machine learning scenario, or maybe it is a common scenario in the python developer community that we think would benefit.

Skills needed:
* Need some python skills 
* .. likely more to come

If you are interested let us know below.

**Comment by siri-rakesh** [comment]
Rakesh Varma Siri - Accenture, India. I am interested.

**Comment by vaughanknight** [comment]
Awesome!  I created a discussion #38 to continue the discussion there! :)

**Comment by mrchrisadams** [comment]
Hey folks, I've referenced this issue from a library with similar goals, because we've realised that it might be a potential consumer of data collated during the GSF data project
