### ISSUE TITLE
🎯 2023-02-01 (Americas/Europe) Carbon Aware SDK Weekly Meeting Agenda

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/carbon-aware-sdk#274]
## Date
2023-02-01 - 3pm UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Introductions
- [ ] Approve Past Meeting Minutes
- [ ] Review Pull Requests
- [ ] Discuss Issues

# PRs

# Issues 

## Discussion 
- [ ]  Decide whether we want to use a single issue to track both meetings

## Action Items
- [ ] 

**Meeting attended by**

**Comment by bderusha** [comment]
Attended

**Comment by Willmish** [comment]
Attended

**Comment by tmcclell** [comment]
Attended

**Comment by FabioTurati-NTT** [comment]
Attended

**Comment by pritipath** [comment]
Agenda:

1. Discuss things that we (Microsoft CSE) are currently working on in the GSF repo
2. High level overview of PRs that are ready for GSF review.
3. General questions about picking things from GSF backlog

**Comment by bderusha** [comment]
Agenda Item: Received feedback from internal team on missing features preventing them from using carbon aware sdk

**Comment by pritipath** [comment]
PRs Ready for GSF review

1. Improve documentation for clarity and consistency -  [Updates to Getting-Started.md and Quickstart.md by Kpopovs1 · Pull Request #251 · Green-Software-Foundation/carbon-aware-sdk (github.com)](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/251)
2. Remove Aggregator reference from GSF library - https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/253
3. WebAPI-CA library integration - https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/245
4. CLI-CA library integration - https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/270
5. Add docs + error checking to improve experience for free trial ElectricityMaps Users - https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/231
6. Added support for Markdown linter GitHub Actions - https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/243
7. Update clients to use Moq for HttpRequests - https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/241

**Comment by FabioTurati-NTT** [comment]
Hi @pritipath, item #5 is "Add docs + error checking to improve experience for free trial ElectricityMaps Users" but the link leads to https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/231, I think you meant https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/267 instead, could you please check?

**Comment by pritipath** [comment]
> Hi @pritipath, item 5 is "Add docs + error checking to improve experience for free trial ElectricityMaps Users" but the link leads to issue #231, I think you meant PR #267 instead, could you please check?

Fixed. Thanks for letting me know.

**Comment by pritipath** [comment]
@Willmish I added the ADR for Aggregator removal in the list of 'Ready for Review' items
