### ISSUE TITLE
Help Us Tell the Carbon Aware SDK Story

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#28]
We need help writing the Carbon Aware SDK Story

* Markdown and documentation on the github project
* Presentation content
* Blog posts
* And more

Reply below and we can start kicking off streams

**Comment by srini1978** [comment]
I am interested in this

**Comment by srini1978** [comment]
[

> I am interested in this
Adding a link to the WIP article . @vaughanknight can you please review

[](https://github.com/srini1978/carbon-aware-sdk/tree/dev/carbon-aware-sdk)

**Comment by aradhika98** [comment]
I am interested too

**Comment by Alyssa-Cooper** [comment]
Happy to help here if the motion is still going! Is anyone leading this effort?

**Comment by kunalmcitm** [comment]
Happy to help if its still on.

**Comment by danuw** [comment]
Hi what is the latest on this? Happy to help too please?

**Comment by tmcclell** [comment]
I am too!

**Comment by macco3k** [comment]
I would love to contribute to documenting the project, but it is quite confusing as it is, both in terms of the sdk intended goal and its internals. I think it would be nice to have a dedicated documentation working group.
