### ISSUE TITLE
Build out a Java Demo using the SDK

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#29]
We are looking to build out a good demo in Java for the SDK.  Demo would be using the REST endpoint or the CLI, with the scenario and demo being something common in Java.

The scenario is yet to be defined.  Please let us know if you have ideas below.

Skills needed:
* Need some java skills
* .. likely more to come

If you are interested let us know below.

**Comment by Yegaaa** [comment]
I m interested

**Comment by vaughanknight** [comment]
Great @Yegaaa! I'll create a discussion in discussion and we can talk about it over there!

**Comment by twpatil** [comment]
I am Interested

**Comment by swetaagr** [comment]
I am interested

**Comment by sharanup** [comment]
> I am Interested

I am Interested. Changing to personal github

**Comment by swapnilguptaTW** [comment]
Hello Folks,
Are we looking to build something from scratch or use something which is existing and plugin our use case in it ?Thoughtworks has a Java starter kit which might be useful and reduce the efforts in developing anything from Scratch. More thoughts on it ?

**Comment by alex-kroll** [comment]
I am interested.

**Comment by souvikdgreat** [comment]
I am Interested

**Comment by fredrhaetw** [comment]
Hello, I am also interested in help on this. :)

**Comment by YaSuenag** [comment]
> Thoughtworks has a Java starter kit which might be useful and reduce the efforts in developing anything from Scratch. More thoughts on it ? https://www.thoughtworks.com/catalyst

IMHO it is better to use Java SE API or to use Spring framework because they are popular and are used all over the world. The demo app with them will be more friendly to understand the SDK for many Java developers.

**Comment by swapnilguptaTW** [comment]
Is anyone working on this ? Should we all connect and discuss more on this. Thoughts plz

**Comment by YaSuenag** [comment]
I think we can start to work for this after merging client generator.
https://github.com/Green-Software-Foundation/carbon-aware-sdk/tree/client-generation-ocw-2/src/clients

**Comment by YaSuenag** [comment]
I'd like to start this work because v1.0 will be shipped soon!

I think I will create SDK client example with Java, and will accept your contributions.

* Pure Java console application
* It calls all of REST endpoint in WebAPI
* Use Maven to build, and generate client code with [Swagger CodeGen](https://mvnrepository.com/artifact/io.swagger/swagger-codegen-maven-plugin) in `generate` goal
* It will be located at https://github.com/Green-Software-Foundation/carbon-aware-sdk/tree/dev/samples

Comments are welcome!

**Comment by YaSuenag** [comment]
I've sent PR for this issue in #150 . Comments / reviews / PRs are welcome.

**Comment by Willmish** [comment]
@YaSuenag , as mentioned on the call, could you add a Dockerfile for the Demo for setup? thanks!

**Comment by YaSuenag** [comment]
@Willmish I added description to use container to build. We can use container without Dockerfile for this purpose.

Unfortunately I don't have Docker and VS Code, so I can't describe about `docker` command and about devcontainer. But I hope this description helps your review.

All comments / suggestions are welcome!
