### ISSUE TITLE
🎯Meeting Agenda 2023-02-14

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#292]
## Date
2023-02-14 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [ ] Approve Past Meeting Minutes
- [ ] Review Pull Requests
- [ ] Discuss Issues
- [ ] Electricity Map Free 

# PRs

# Issues 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by vaughanknight** [comment]
Attended

**Comment by danuw** [comment]
Attended

**Comment by FabioTurati-NTT** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by vaughanknight** [comment]
Discussion was had regarding running a planning session for the roadmap moving ahead.  Aim is to have participation from all GSF members across timezones so likely to have an Asia/EMEA session and a America's time zone session.  These would be 2 hours long to capture requirements at a high level, and then follow up with a session a month later to go over the captured information in detail / playback this information and ensure people are aligned.

This would then play into a roadmap and kanban board to capture the information, in addition to setting the scene for all current work in progress by other parties (such as the Microosft team currnetly working on features) so that there is a clear overview of the roadmap, features in progress, and features pending.

**Comment by vaughanknight** [comment]
Need to add changelog guidance to PR template

**Comment by vaughanknight** [comment]
Vaughan to discuss with Microsoft the current state and PR's to finalise 1.1 and form a release hopefully next week.

**Comment by Willmish** [comment]
Approved and closed on #301
