### ISSUE TITLE
Move files in carbon-aware-sdk folder into root folder

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#3]
I believe these files were added in a replicated folder name by accident.   Files in this location to be moved to root folder.

**Comment by vaughanknight** [comment]
@seanmcilroy29 - I was working locally and realised I had a duplicated folder name staring at me.  Was this meant to be a duplicated folder?  I can fix easily just checking what is standard.

**Comment by Willmish** [comment]
@vaughanknight The carbon-aware-sdk folder is there with a different README.md file, the LICENSE and some placeholder files. Can open PR to clean this up, but maybe we want to keep some of its content: https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/carbon-aware-sdk/Readme.md

Not sure what the purpose if the [index.yaml](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/361814f26ada3d6e41ffdc1a149fc1194cd39943/carbon-aware-sdk/index.yaml) file is, do we need it?

**Comment by Willmish** [comment]
To check with @seanmcilroy29

**Comment by vaughanknight** [comment]
Sean gave guidance to remove the folder.  @Willmish to create a PR for this one.

**Comment by vaughanknight** [comment]
@vaughanknight to talk to @Willmish regarding files that may move to root folder.

**Comment by vaughanknight** [comment]
Let's remove the folder and any documenation can be leveraged if required to support and supplement other documentation.

**Comment by vaughanknight** [comment]
I'll review the PR and merge prior to closing.

**Comment by dohafernandez** [comment]
@vaughanknight which PR are you referring to here?

**Comment by vaughanknight** [comment]
Closed and merged.
