### ISSUE TITLE
🎯Meeting Agenda 2023-02-21

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#301]
## Date
2023-02-21 - 8am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes
- [x] Review Pull Requests
- [x] Discuss Issues
- [x] Roadmap Planning Meeting
- [x] ElectricityMaps

# PRs

# Issues 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by Willmish** [comment]
Attended

**Comment by FabioTurati-NTT** [comment]
Attended

**Comment by vaughanknight** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by nttDamien** [comment]
Attended

**Comment by danuw** [comment]
Attended

**Comment by Willmish** [comment]
Roadmap planning discussion:
- Might do a "lighter" version with fewer people mid-March
- Later gather leads from other GSF projects + other and do a longer session 
- Need to prepare Kanban boards (what features we might want, what is available to be picked up, what is being worked on by who)

**Comment by Willmish** [comment]
Update from Ciril from EM on free API vs Paid:

Hi Willmish, I was able to get some information from our product team.

As you highlighted, right now both the free version and the pro version of our API have two different access points and we have realised the friction this can create. Our product team is currently scoping the work on merging them but the work on this will not start before March. We typically work in cycles (~ 1 month) and we expect this to be merged within the next cycle. Note however, that we cannot guarantee that.

I think it is best to assess how much time building a separate support would require of you and what timeline you have laid out.

If there are any questions or comments on the above, please let me know.

**Comment by vaughanknight** [comment]
Dan discussed: Github workflows and cleaning them up, bringing things together, deploying to 1 endpoint, and a couple more endpoints - main branch, dev branch, and one potentially what is in PR's.  This helps with prevalidation.
