### ISSUE TITLE
[Bug]: Carbon Aware Azure Functions / nuget with -IncludeReferencedProject

### ISSUE THREAD

**Issue by georgekosmidis** [Green-Software-Foundation/carbon-aware-sdk#306]
### Contact Details

georgekosmidis@outlook.com

### What happened?

Hello all,

I ve been working on a small piece of code that brings the Carbon Aware SDK to Azure Functions (you can check it here: https://github.com/georgekosmidis/Greenhopper).

I ve been pulling Carbon Aware SDK repo as a submodule and using parts of it in my solution as a code reference. This works well for developing but when I am trying to pack it as nuget with `-IncludeReferencedProjects` i get the following error (upon referencing the nuget package):

`Assembly 'Greenhopper' with identity 'Greenhopper, Version=0.3.4.0, Culture=neutral, PublicKeyToken=null' uses 'Microsoft.Extensions.Hosting.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.Hosting.Abstractions' with identity 'Microsoft.Extensions.Hosting.Abstractions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'`

Is there a chance we could somehow align on the versions, at least up until there is nuget package?

Thanks!

P.S.

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by georgekosmidis** [comment]
Hey @danuw,
this is the issue requested at https://github.com/Green-Software-Foundation/carbon-aware-sdk/discussions/304

**Comment by Willmish** [comment]
Hi @georgekosmidis  - thanks for raising this. From what I understand you are in contact with @vaughanknight as well - we just had a weekly project sync with other members of the GSF (#314 ) during which your issue was briefly discussed. 

There will be further discussions on this, but it would be helpful if contributors from #224 could look at this as it might be related? (@pritipath ) Can anything be done on this without releasing a CA SDK NuGet package ourselves? Would this require us to keep updating dev with most recent package versions?

**Comment by Willmish** [comment]
What I forsee as a possible solution is v1.1 being on track to be released soon, and it most likely has all the features you are currently using and you will be able to align to that. But lets hear others' input as well

**Comment by georgekosmidis** [comment]
I can happily say, that after just a few hundreds of attempts, I finally managed to have a nuget package working :):):)

**Greenhopper v1.0.0 is out there!**

**Comment by danuw** [comment]
That is great news - well done. Anything you might be able to contribute back to help improve the repo?

If nothing, please can you confirm if we can close this issue?

**Comment by georgekosmidis** [comment]
I would very much like to see a nuget package out of this repo as it will simplify usage all around, and I am willing to contribute to that, but for now no, i do not have anything else to add.

Thank you!
