### ISSUE TITLE
[Action] DCO enabled on GSF GitHub

### ISSUE THREAD

**Issue by Sealjay** [Green-Software-Foundation/carbon-aware-sdk#309]
Developer Certificate of Origin[^1] is being enabled at the Green Software Foundation:
https://github.com/orgs/Green-Software-Foundation/discussions/5

If you primarily change markdown files and other documents through the web interface, you should notice minimal changes.

Software developers will need to sign their commits on the commandline with `-s`.

Once enabled, your project will be able to accept code and text via Pull Request, from people that are not at Green Software Foundation member organisations.

For more information on the impact, rationale, and to ask any questions, [please see the discussion](https://github.com/orgs/Green-Software-Foundation/discussions/5).

[^1]: https://developercertificate.org/

**Comment by Willmish** [comment]
FYI: @bderusha @pritipath @gfmatthews @juzuluag @JenMadiedo

**Comment by Sealjay** [comment]
> If you have to modify some commits to add the sign-offs, an easy way is to use
> 
>     * `git rebase -i <one commit before the first one you want to sign-off>`,
> 
>     * change every action to `edit` instead of the default `pick`,
> 
>     * then, for every commit, run
>       
>       * `git commit --amend -s`
>       * close the editor with ctrl-x
>       * `git rebase --continue`
> 
> 
> That should do it!

Thanks @FabioTurati-NTT ! Quoted you here: https://github.com/orgs/Green-Software-Foundation/discussions/5#discussioncomment-5336378

**Comment by Willmish** [comment]
See example of such remediation commit here: https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/298/commits/9d7230e367e5c40ff71128d3efdb7bcd5b957b20

**Comment by FabioTurati-NTT** [comment]
Hi @Willmish , I agree that a remediation commit is better, because it doesn't require rewriting history, and it's also faster. If I need to do it again I'll certainly follow this approach!

**Comment by Sealjay** [comment]
Perfect - @FabioTurati-NTT you also shouldn't be required to sign these commits (although it's good practice), as this check is only applied to code submitted by non-GSF members. @seanmcilroy29  may need to check you've been invited to the GSF org

**Comment by seanmcilroy29** [comment]
@FabioTurati-NTT - I've just invited you to join
