### ISSUE TITLE
Automated deployment to AWS ECS

### ISSUE THREAD

**Issue by ng-druid** [Green-Software-Foundation/carbon-aware-sdk#311]
### What happened?

As an AWS user I would like to deploy the api on AWS ECS instead of Azure.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by danuw** [comment]
Hi @ng-druid , thank you for creating this (feature request?).

Would you be able to expand on this issue please?

What are you expecting please? 
Feel free to further detail the expected result (with initial acceptance criteria), link to similar features examples and (link to or explanations about) what you may have already done if at all so we that we can understand how to take this further.
