### ISSUE TITLE
[Bug]: Intensity Data Inaccuracy

### ISSUE THREAD

**Issue by ng-druid** [Green-Software-Foundation/carbon-aware-sdk#315]
### Contact Details

rollthecloud@gmail.com

### What happened?

We are generating a report of carbon intensities for each azure region periodically every five minutes. This report can be found below for the time of this posting.

https://github.com/rollthecloudinc/hedge-objects-prod/blob/d1d39f9c5db6a9b1d57163366c1ace52809f1730/renewable-report/report.json

When uksouth and ukwest are compared with the current WattTime map the numbers don't seem to add up. When nearly all European nations are in yellow or red yet the intensity score for uksouth and uknorth are 427. The data seems to indicate they are the lowest intensity on the map. However, the lowest intensity on the map is Norway which is the only green European nation. Norway at this time had a carbon intensity of 438. Something seems off here.

Another important note is that the carbon aware api isn't calculating Norway. Therefore, we have taken it upon ourselves to use the WattTime api as a fallback for the current intensity level of Norway.

Some this data doesn't seem to add up when compared to the WattTime current intensities.

<img width="1436" alt="Screen Shot 2023-03-08 at 6 49 36 PM" src="https://user-images.githubusercontent.com/73197190/223880326-931b383a-f7fd-4e79-b0e9-97305c54cd70.png">

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vaughanknight** [comment]
Are you comparing marginal to average?  Marginal is what would be created if you drew 1kwh of energy, average is the total.  Not sure what it might be but that was something I think that might make it different.  API gives marginal, not average for WattTime data.  Do you have a link to the page you have screenshot above please?
