### ISSUE TITLE
[Bug]: Fix and update doc deployment workflow

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#344]
### What happened?

The following worklfow builds documentation that has not run for over a year.
https://github.com/Green-Software-Foundation/carbon-aware-sdk/actions/workflows/pages/pages-build-deployment

Do we need to fix so the latest gets deployed in a format that may be issue to consume by others?

Other projects in GSF use [Docasaurus](https://docusaurus.io/) to build their documentation, an example such project is : https://github.com/Green-Software-Foundation/sci-guide , currently deployed to : https://sci-guide.greensoftware.foundation/

Best solution to this issue would involve - restructuring the current [docs](/docs) to be buildable and deployable as a Docasaurus project on github pages.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Willmish** [comment]
We definitely want the latest docs to be reflected on the website. To be honest we should consider in general whether we should have a web deployed docs or keep it purely in GH.

I personally am for maintaining both, ideally keeping all documents in the docs folder so they are buildable with a tool like Sphinx https://www.sphinx-doc.org/en/master/ , we can then add a GH action that redeploys the docs on any changes to the docs/ folder

@vaughanknight @danuw  what do you guys think?

**Comment by Willmish** [comment]
Feedback from the Open Source WG: other GSF projects (SCI ) use docasaurus which use mdx files and would require some modification of existing documentation, but we would then stick with consistency

**Comment by Willmish** [comment]
Update during meeting #355 : no update on this yet, @danuw currently looking at other issues.

**Comment by Willmish** [comment]
Update #358 : no update, open for contributors to pick up

**Comment by danuw** [comment]
Shouldn't we reopen this? Looks like it was closed by mistake @Willmish 

(Started taking a look at docusaurus. 

Looking at how it works for now and how to leverage the root docs folder ideally...)

**Comment by danuw** [comment]
@YaSuenag branch is on my fork at the mo.
To https://github.com/danuw/carbon-aware-sdk.git
   ede7ab7..fbc602c  docs/docusaurus-setup -> docs/docusaurus-setup
   
I have pushed everything - note I have not yet moved files from docs to casdk-docs/docs

Let me know if you need my help but I have a feeling what you are after is another folder (like blog and docs)

**Comment by Willmish** [comment]
form #384: @danuw to share screenshots from his local demo using the existing docs folder in the `dev` branch

**Comment by danuw** [comment]
Attaching some screenshots of what we currently have

Mobile and Desktop of the home page
![screencapture-localhost-3000-carbon-aware-sdk-2023-08-22-00_47_01](https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/8134789/9125c2b3-3f98-42df-854d-1c36bd5da787)

![screencapture-localhost-3000-carbon-aware-sdk-2023-08-22-00_47_37](https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/8134789/49567b01-e8cd-4420-8585-4157882c3deb)

Tutorial homepage and sidebar for now
![screencapture-localhost-3000-carbon-aware-sdk-docs-intro-2023-08-22-00_48_53](https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/8134789/cd30edfa-e914-4251-be1c-030386d6719b)

**Comment by danuw** [comment]
done some clean up 

<img width="449" alt="Screenshot 2023-08-22 at 01 56 23" src="https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/8134789/a2621236-dd4f-4686-82ed-89f2ea9daabd">

which mostly expanded shows this...
<img width="446" alt="Screenshot 2023-08-22 at 01 56 07" src="https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/8134789/f0e26b19-965d-4efc-8361-e6d8a331aef2">

**Comment by danuw** [comment]
Main challenge remaining is around sample docs... on how to integrate with it...

**Comment by danuw** [comment]
Hi @osamajandali, @jawache suggested to get in touch with you about this.

We are trying to revive the docusauraus/docs website for the repo. I currently have a branch that compiles to the above screenshots.

Considerations:
- using `/casdk-docs` folder for docusaurus
- copied `/docs` folder (into `/casdk-docs`) for the docs to show (I could not find a way to link to docs outside of the folder - having the docs under casdk has the expected benefit or UI updating and bad links being flagged as docs are updated

Latest hurdle to tackle is around docs available in the `/samples`. Ideal plan was to surface the `.md` files from the `/samples` folder (so have a top level section in the navigation for `samples` in above or below the `architecture` one). The issue is the same as with docs though it does make as sense in this case (vs moving the docs) to be in that sub folder. Samples should stay out of the folder. There is always the option to copy the files at compile time, but then would need to stop the process and relaunch for the file changes to be taken into account, so less than ideal.

Are you able to help? do you have any suggestions? Let me know 
(Feel free to connect on slack too if easier so we can maybe talk about it.)

**Comment by zanete** [comment]
Capturing status on the weekly call:
- @osamajandali will investigate this week

**Comment by osamajandali** [comment]
Hello @danuw,

I apologize for my delayed response as I was occupied with various tasks. After reviewing the code, I understand that you wish to maintain the current repository structure while also having the documentation appear on the docs website. The issue you are facing is that you are unable to reference docs outside of the `/casdk-docs` folder. This is because docusaurus can only access files within its own folder.

Manually copying the files is not an ideal solution as you mentioned. There are two options available to you:

1. The complex way: Monorepo style, which involves making several changes and setting up multiple processes.
2. The recommended way: Using a Github action, you can set up a workflow that automatically copies files whenever a commit occurs. You can specify which files from which folder should be copied to which folder in `/casdk-docs`, and afterward you need to add to the workflow a build flow that will be triggered after this process to compile the copied markdowns in pages.

If you require any assistance with this setup, please let me know. 

Additionally, I would like to note that there is a template available for the docs website that has all the necessary setup for having a GSF branded docs. You can use it or extract the style from it. Here is the [template link](https://github.com/Green-Software-Foundation/doc-template).

**Comment by zanete** [comment]
@danuw can you confirm if you need any more of @osamajandali help here?

**Comment by danuw** [comment]
Hi @zanete just on that part (below) in case @osamajandali has any tips or scripts we can reuse and generally review my last comment / summary above.

> Let me know if you have anymore thoughts and scripts/tips on get the fules to copy

If not I think we are good. 

Thank you for checking in

**Comment by osamajandali** [comment]
Hey @danuw, I don't have one but I wrote a simple script in my own just to inspire you. Below is an explained workflow example of what I have in mind using github actions. Something like below will do everything automatically without any interference from anybody.

```yaml
name: Copy Files during Build

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Copy Files
      run: |
        # Replace 'source' and 'destination' with the actual paths to your files
        cp -r source/* destination/
      working-directory: ${{ github.workspace }}

    - name: Commit and Push Changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Copy files during build"
        git push
      working-directory: ${{ github.workspace }}
```

In this workflow:

1. It triggers on a push to the "main" branch. You can change the branch as needed.

2. It checks out the repository using the `actions/checkout` action.

3. It uses the `cp` command to copy files from the "source" directory to the "destination" directory. Make sure to replace "source" and "destination" with the actual paths to your files.

4. It commits and pushes the changes back to the repository. The Git configuration is set with a user name and email for the commit.

**Comment by zanete** [comment]
hi @danuw, thank you for the clarification, does the above comment help and can we remove this from Osama's workload?

**Comment by danuw** [comment]
Thank you @osamajandali the copy task is mostly what I was after I think.
Although I may especially be after it in the process of running docusaurus locally (so it reflects on the local machine too - if the files get moved at check in, we can always do that manually too and create in the right destination though it does not feel like the right place to store).
Will come back to you when I have had a chance to checking this.
Thank you again for the snippets and tips

**Comment by danuw** [comment]
Pending action here is that the deployment pipeline does not error but only works partially.

It deploys to `https://green-software-foundation.github.io/carbon-aware-sdk/` but it is missing the layout (navigation and header bar).

This shows that changes get deployed - although I could test by adding a file in particular and removing it afterwards to make sure updates do occur (will test that now and report back)
https://green-software-foundation.github.io/carbon-aware-sdk/docs/overview

**Comment by danuw** [comment]
All sorted - basically I still needed the config to deploy from GitHub pages branch even though I have my own workflow to deploy.

So left to do:
- [ ] logic to move the samples folder at build in the pipeline
- [ ] condition to make sure website only gets updates for main or dev updates - cc @vaughanknight we should confirm when we publish latest updates and if there are maybe options to have a dev instance and a main instance, but will assume we deploy the latest from dev for now
- [ ] apply the banner referenced in #416

**Comment by zanete** [comment]
thanks @danuw, would anything in that list you've added need input from @osamajandali or can I remove his name from the assignee list? 🙏

**Comment by danuw** [comment]
Hi @zanete you can remove. Thank you

**Comment by danuw** [comment]
(Fyi a copy paste of the themes from IF docs did not work out of the box, so something to come back to, after 1.3 release)

**Comment by danuw** [comment]
Workflow works

<img width="1636" alt="Screenshot 2024-02-11 at 23 44 11" src="https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/8134789/77ef83ab-74b5-4c90-a04e-d73585d8315a">


Remaining :
- [ ] rebase with dev
- [ ] sort out warning from samples folder (.md files broken links)
- [ ] cleanup docs folder

**Comment by danuw** [comment]
Order for reference 

1. Project overview (ReadMe)
2. How to contribute (contributing.md )
3. End User Guide (enablement.md)
4. Test coverage
5. Fit within GSF Theory of Change
6. adopters.md
7. security.md

**Comment by Sophietn** [comment]
@danuw happy to close this issue off now? 
(Docusaurus found at https://carbon-aware-sdk.greensoftware.foundation)

**Comment by danuw** [comment]
Sure that can probably be be closed but still waiting for PR to be approved by the team.

@zanete yes you can remove his name if you need. Thank you

**Comment by vaughanknight** [comment]
<img width="1176" alt="image" src="https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/252951/543df8c0-3cc0-4645-b4e6-bb4358bf999a">
Carbon Aware SDK Tutorial?

**Comment by vaughanknight** [comment]
<img width="648" alt="image" src="https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/252951/175da2d2-5f8b-48c9-ab4b-6c21fac0e5c6">
Tutorial link in the footer goes to 404
