### ISSUE TITLE
[Feature Contribution]: Multiple data source support

### ISSUE THREAD

**Issue by YaSuenag** [Green-Software-Foundation/carbon-aware-sdk#345]
### What happened?

I proposed this feature in https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/343#issuecomment-1531014957 .

Carbon Aware SDK supports just one data source as following:

```
{
  "DataSources": {
    "EmissionsDataSource": "ElectricityMaps",
    "ForecastDataSource": "WattTime",
```

Granularity and covered area vary in each data souces. Some SDK users want to use WattTime as a first priority, but they might want to use ElectricityMaps when they want to know emission data of uncovered area in WattTime.

So I'd like to propose mutiple data source support as following:

```
{
  "DataSources": {
    "EmissionsDataSources": ["WattTime", "ElectricityMaps"],
    "ForecastDataSources": ["JSON", "WattTime", "ElectricityMaps"],
```

In above case, both `EmissionsDataSouce` and `ForecastDataSouces` are array. Lower index is higher priority. For example in `EmissionData`, `WattTime` is the highest priority, but no emission data for given location in WattTime, it would fallback to `ElectricityMaps`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by bderusha** [comment]
@YaSuenag This seems worthy of an ADR.

**Comment by YaSuenag** [comment]
@bderusha Can we converge this proposal to [ADR-0006](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0006-data-source-registration.md) ? They are strongly related, and I guess this proposal would make big change from ADR-0006. So I think it makes sence to work together.

**Comment by bderusha** [comment]
This seems like it is more related to [ADR-008](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0008-data-source-configuration.md). Either way, happy to collaborate.

My personal preference is to create new ADRs and add a reference to existing ADRs impacted by the new one.

For example:
- Create `ADR-0016: Multiple Data Source Support`
- Update `ADR-0008` status to "superseded by [ADR-0016](#)" 

Unless @vaughanknight or @Willmish has a different preference for this project

**Comment by Willmish** [comment]
From call: Data from WattTime and data in ElectricityMaps is different - (one uses marginal the other uses average( might not be comparable between different locations using different data sources.

So important thing to point out here is, how do we ensure users are aware where the data comes from and that it might be different/not comparable between different locations if used from different datasources (marginal vs average)

**Comment by Willmish** [comment]
Update from meeting #355: not crticial  for 1.1, rather a feature for 1.2. Open to discussion
