### ISSUE TITLE
[Bug]: Release not triggering for pre-release

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#360]
### What happened?

After merging the latest changing allowing to create packages for new releases, we experienced an issue where it did not trigger when creating a new release.
It was tested on a different repo where the workflow triggered for [release](https://github.com/danuw/carbon-aware-sdk/actions/runs/5174593345) and [pre-release](https://github.com/danuw/carbon-aware-sdk/actions/runs/5174676223) 
[as described in documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release).

Could this be a permission issue? @vaughanknight might you be able to create a test release so we can confirm please?

cc @YaSuenag 

### Relevant log output

There are no logs but this can show that it was not triggered https://github.com/Green-Software-Foundation/carbon-aware-sdk/actions?query=branch%3Av1.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danuw** [comment]
Thank you @vaughanknight, it looks like it is a permissions issue.

@YaSuenag, any idea which one it may be please? https://github.com/Green-Software-Foundation/carbon-aware-sdk/actions/runs/5175437197/jobs/9323018801

Speak in the morning

**Comment by YaSuenag** [comment]
I'm not sure, but it may come from `admin:org_hook`. https://docs.github.com/en/rest/orgs/webhooks?apiVersion=2022-11-28#scopes-and-restrictions

I guess `admin:org_hook` does not granted to all of maintainers of CASDK.

**Comment by YaSuenag** [comment]
> I'm not sure, but it may come from `admin:org_hook`.

But other workflows are triggered - so it might not be caused by `admin:org_hook`...
