### ISSUE TITLE
[Bug]: Some GHA were failed due to empty workflow

### ISSUE THREAD

**Issue by YaSuenag** [Green-Software-Foundation/carbon-aware-sdk#382]
### What happened?

Following actions were failed because workflow file is empty (all lines are commented out). Is it temporally?

* .github/workflows/run-sdkCLI-githubaction.yml
* .github/workflows/2.a-deploy.yaml
* .github/workflows/run-sdkCLI-githubaction.yml

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danuw** [comment]
Hi @YaSuenag , I noticed too, and while that was temporary, I believe we should just remove them and can reintroduce later to remove the failing (and confusing builds - my bad as I thought commented out workflow would not event run)

**Comment by Willmish** [comment]
@danuw could you pick this up in free time?

**Comment by danuw** [comment]
Just seen this bug fixed it earlier this week in the docs branch.

Will link
