### ISSUE TITLE
[Action] Regular OSS WG Update

### ISSUE THREAD

**Issue by Sealjay** [Green-Software-Foundation/carbon-aware-sdk#395]
- [ ] Please make sure your calendar times are added to the OSS WG website in a PR: https://github.com/Green-Software-Foundation/opensource-wg/blob/main/docs/calendar.mdx
- [x] Please add your update to the issue in the WG https://github.com/Green-Software-Foundation/opensource-wg/issues/48

**Comment by danuw** [comment]
@Willmish are we good with this one? Can we lose?
