### ISSUE TITLE
Build out demo leveraging data centre names, across AWS, GCP, and Azure

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#4]
As a Green Developer I want to know the carbon emissions across data centres that I deploy in on multiple clouds so that I can make the greenest software decisions.

* Leverage datacentre names
* Make it modular
* DOES NOT - need to have real data (for now)

**Comment by vaughanknight** [comment]
This is complete for AWS and Azure in the branch I'm working on currently.  I will look at extending to GCP.

**Comment by Willmish** [comment]
Not needed.
