### ISSUE TITLE
Publish nuget package to consume

### ISSUE THREAD

**Issue by luwangshell** [Green-Software-Foundation/carbon-aware-sdk#40]
It will be easier for other libs or application to consume or implement the sdk by referencing with published nuget package.

**Comment by luwangshell** [comment]
@vaughanknight I would like to work on this one. Could you advise how to proceed? It seems I cannot assign this one to myself. thank you.

**Comment by tw-kishan-vaishnav** [comment]
I would like to help in this ticket. This is the first time I will be contributing. So, can you please explain what needs to be done and how.

**Comment by tw-kishan-vaishnav** [comment]
Can we use the nuget.org repository? I am new to docker container. So, not sure how to build them.

**Comment by luwangshell** [comment]
I am fine either way, as long as it can be consumed easily. @vaughanknight  thoughts?

**Comment by tw-kishan-vaishnav** [comment]
I think below Class Libraries need to be published:

- CarbonAware

- CarbonAware.Plugins.BasicJsonPlugin

I have created .nupkg files for both the projects with version 1.0.0. 

Please provide apiKey to publish them to a repository.

Thanks @tw-arun-ap for support.

**Comment by luwangshell** [comment]
@tw-kishan-vaishnav thanks! could you publish to the GitHub package? https://docs.github.com/pt/packages/learn-github-packages/publishing-a-package

**Comment by yelghali** [comment]
hello @tw-kishan-vaishnav, I have started building DevOps/DevSecops pipelines for the SDK (CLI as Docker Image & Github Action ; API as Docker image, Doc website, code security scanning, etc.)

I'll be happy to collaborate with you to build the dotnet package (in CICD Github Action), and publish it as @luwangshell suggested.

lopping @vaughanknight, I propose to take higher level conversation on the artifacts to be published for the SDK (for instance dotnet package or Docker Image):

Started in this link an initial proposal (to be discussed / enhanced)
https://github.com/Green-Software-Foundation/carbon-aware-sdk/discussions/46 

thank you
Yassine

**Comment by vaughanknight** [comment]
Closing this one out as after much deliberation we do not want to automatically publish nuget packages (for now).  Primarily this is because it will require long term agreement to manage and support.  This may come back at some point but right now it's not a priority.  This is also because client generation will be included, and as such teams may manage their own packages within a large company (and would not be using public packages anyway)
