### ISSUE TITLE
[Feature Contribution]: Export carbon intensity to Prometheus

### ISSUE THREAD

**Issue by tiwatsuka** [Green-Software-Foundation/carbon-aware-sdk#400]
### What happened?

Carbon Aware SDK can provide carbon intensity data.  When the data are used combined with electricity consumption of the nodes that software are running on, the carbon emission can be calculated. This can be helpful for users to building and operating carbon-aware software.

Regarding the electricity consumption, there are several means to monitor with Prometheus. (e.g. [node-exporter](https://github.com/prometheus/node_exporter), [redfish-exporter](https://github.com/jenningsloy318/redfish_exporter), [kepler](https://github.com/sustainable-computing-io/kepler).) So it is convenient that also Carbon Aware SDK exports carbon intensity to Prometheus.  It will be enable uses to monitoring the carbon emissions of software with the popular tools.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by vaughanknight** [comment]
An interesting aspect here is to have a container, that is in a "tools" folder, which runs in the kubernetes cluster, so people can just grab it, and it emits prometheus events, and is configured with the location of the CA SDK as environment parameters (or whatever) to the container. 

Promeetheus emitter pod (maybe as a daemon) --> CA SDK in a pod--> <data souce i.e. ElectricityMaps/WattTime> 

`This allows for 1 cluster to 1 CA SDK pod in the clust,er` or `Many clusters to 1 CA deployment outside the cluster`

**Comment by Sophietn** [comment]
Blocked until https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/404 is done (.NET 8.0)
