### ISSUE TITLE
[Feature Contribution]: Upgrade .NET version to .NET 8

### ISSUE THREAD

**Issue by tiwatsuka** [Green-Software-Foundation/carbon-aware-sdk#401]
### What happened?

.NET 8 that is the next LTS version of .NET is planned to be release Nov. 2023.  Carbon Aware SDK should be upgraded to .NET 8 because using the latest LTS is good practice, generally. 

FYI, .NET 8 contains important improvements to implement #400. 
* https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#metrics
* https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#imeterfactory-interface

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by Sophietn** [comment]
Blocked until https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/420 is done

**Comment by tiwatsuka** [comment]
Closed by #493
