### ISSUE TITLE
[Feature suggestion]: embrace a more holistic approach

### ISSUE THREAD

**Issue by ldevernay** [Green-Software-Foundation/carbon-aware-sdk#403]
### Contact Details

ldevernay@greenspector.com

### What happened?

Hi,
Following a discussion on Linkedin, your tool is really great but could benefit from a more holistic approach. 
Even if more and more people are (roughly) aware of carbon emissions related to digital services, other factors should be taken into account. Environmental factors but, ideally, other factors for sustainability (such as security, privacy, sovereignty and so on). 

I don't necessarily know all the details on how carbon-aware SDK works, sorry in advance for my possible mistakes.

Focusing on carbon could lead to carbon tunnel vision (https://reimaginesustainability.com/from-a-carbon-tunnel-vision-to-a-holistic-collaboration-approach/) with a risk of missing important environmental impacts (such as water and, paradoxically, carbon emissions... more on this later). It could lead to impact transfers or even aggravating impacts on water by transferring workload on data centers with mostly low-carbon energy but heavy water consumption (as might be the case with nuclear energy, for instance). 
Plus, implementing other factors might raise awareness about them. I see more and more people aiming for green hosting by looking at the carbon impact of energy but the issue is wider than that (as detailed here : https://greenspector.com/en/comparison-of-web-hosting-offers-selected-for-their-environmental-commitments/). 

So, the idea would be : how can you go further on environmental impacts?
For instance, could an equivalent to ElectricityMap be found for water-related issues? 
I found this but not sure it is up-to-date : https://datasets.wri.org/dataset/aqueduct-global-maps-21-data
Also, the CUE (even if renewables are involved, some data centers still emit carbon) and WUE from data centers could be taken into account.

Sorry if this sounds messy but the point here is to start a discussion. 
See you soon,

Laurent.

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by buchananwp** [comment]
Thanks for sharing. I do think water-aware computing would be a great expansion. Hoping someone can pick this up!

**Comment by danuw** [comment]
cc @vaughanknight
