### ISSUE TITLE
Init  Website for SDK Documentation, deployed to Github Page

### ISSUE THREAD

**Issue by yelghali** [Green-Software-Foundation/carbon-aware-sdk#41]
The objective is to simplify adoption of the SDK by providing a website for documentation, demo, use cases, etc.

Proposal for solutions:
* Templating: https://docusaurus.io/
* Deployment Github page

An initial version can be found in : https://green-software-foundation.github.io/carbon-aware-sdk/

**Comment by danuw** [comment]
Hi @yelghali , that looks great. Can I confirm how that website gets updated? Would this repo need to follow a specific structure so that the website gets updated automatically (and stays in sync) please?

**Comment by danuw** [comment]
Linking https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/344 to this
