### ISSUE TITLE
Update documentation for How to contribute (contributing.md )

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/carbon-aware-sdk#410]
written by @Sophietn updating issue
Should cover information on current contributors
And who can contribute - GSF member orgs permission vs member of public
How they can contribute 
eg. public can raise an issue, raise a PR?, start a discussion thread with questions 
member orgs can join weekly meeting calendar invite link, contribute to PRs
who can merge PRs etc

**Comment by Sophietn** [comment]
From https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/423: Update to docs: Release schedule - "at most once per month, as frequent as possible" to update in README.md and CONTRIBUTING.md

If we need a security release - we prioritise that.
Documentation release can happen anytime.
