### ISSUE TITLE
Update documentation for End User Guide (enablement.md)

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#412]
Covering why people should and how people can start using our released tool

**Comment by Willmish** [comment]
Similar to original getting started guide current overview file? https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/overview.md

Or quickstart: https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/quickstart.md

**Comment by rinikeda** [comment]
I'm working on this issue.

**Comment by YaSuenag** [comment]
@Willmish @Sophietn 
He is my colleague, and I will support him. So please assign this task to @rinikeda !

**Comment by Sophietn** [comment]
Hi @rinikeda apologies I should have said before, please can you fill out our [Registration form](https://greensoftware.foundation/onboarding/) and [subscribe](https://greensoftware.foundation/subscribe/) to the project

**Comment by rinikeda** [comment]
@Sophietn Thank you for the reminder. I submitted the forms.

**Comment by rinikeda** [comment]
@Sophietn @YaSuenag 

I'm preparing the table of content in enablement.md. I appreciate it if you review it and provide your comment.

---
* What Carbon Aware SDK provide you?
    rewrite [Overview in overview.md](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/overview.md#overview)
  * CLI
  * WebAPI
  * SDK
  * Use cases
    (summarize adoptors.md)

* How to use Carbon Aware SDK?
  * pre-requisities
    * data sources
      rewrite ["Data Sources" in overview.md](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/overview.md#data-sources) and summarize [selecting-a-data-source.md](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/selecting-a-data-source.md)
    * Interface-specific requirement
      rewrite prerequisities for using [CLI](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/quickstart.md#setting-up-the-cli) and [WebAPI](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/quickstart.md#setting-up-the-web-api)
  * CLI
    transribe [the section "Using the CLI" in quickstart.md](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/quickstart.md#using-the-cli)
    * setup
    * usage
  * WebAPI
    * setup
      * deploying with container
        transcribe [the section "Publish WebAPI with container" in overview.md](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/overview.md#publish-webapi-with-container)
      * deploying with Kubernetes
        transcribe [the section "Publish WebAPI on Kubernetes with Helm" in overview.md](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/overview.md#deploy-web-api-on-kubernetes-with-helm)
    * usage (how to call API)
      * call WebAPI using CLI
        transcribe [the section "Calling the Web API via command line" in quickstart.md](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/quickstart.md#calling-the-sdk-via-cli)
      * call WebAPI using client libraries
        transcribe [the section "Calling the Web API via client libraries" in quickstart.md](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/quickstart.md#calling-the-web-api-via-client-libraries)
  * configurations  
    transcribe [the section "Configuration" in overview.md](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/overview.md#configuration)
---

**Comment by Sophietn** [comment]
Hi @rinikeda Thanks for picking this up! That looks great. 
No need to repeat the use cases or summarise the adopters.md, just a link out to it would be helpful

**Comment by rinikeda** [comment]
@Sophietn 
> No need to repeat the use cases or summarise the adopters.md, just a link out to it would be helpful

Thank you for your comment! I'll just provide a link to it.
I'm going to prepare the document.

**Comment by rinikeda** [comment]
@Sophietn @Willmish @YaSuenag 
I'm sorry for the delay. I've prepared the manuscript.
I would appreciate it if you provide comments on it.
