### ISSUE TITLE
Update documentation of Usefulness (adopters.md)

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#414]
Evidence of project usefulness, through real world use cases in the production environment, including testimonials

**Comment by tkuramoto33** [comment]
@YaSuenag I would like to work on this issue. Could you support me?

**Comment by YaSuenag** [comment]
> @YaSuenag I would like to work on this issue. Could you support me?

Sure!

@Willmish @Sophietn
He is my colleague, and I will support him. So please assign this task to @tkuramoto33

**Comment by Sophietn** [comment]
Hi @tkuramoto33  apologies I should have said before, please can you fill out our [Registration form](https://greensoftware.foundation/onboarding/) and [subscribe](https://greensoftware.foundation/subscribe/) to the project

**Comment by tkuramoto33** [comment]
@Sophietn Thank you for your comment! I have done it.

**Comment by tkuramoto33** [comment]
@Sophietn 
Sorry for the delay, but I have created a Draft PR. 
Could you review it and provide your candid feedback?

In addition, are there any other examples of adopters that should be included in adopters.md?
I would like to add them to adopters.md if possible.

**Comment by Sophietn** [comment]
Hi @tkuramoto33 thanks for making a start! The format looks fine. Nice link for UBS.
But the scope of the issue is to add the use cases too. I'm new to the project so I'm not familiar myself - I've heard Microsoft, maybe Shell. How are NTT data using the tool?

**Comment by danuw** [comment]
Adding content about Vestas mentioned here https://www.youtube.com/watch?v=QpRM698cp1A

More details can be found here... https://www.youtube.com/watch?v=4zKSSK8BdN8

**Comment by tkuramoto33** [comment]
@danuw Thank you! I have added a row for Vestas. (Instead of the first YouTube link, I would like to use https://customers.microsoft.com/en-in/story/1700690084732107853-vestas-energy-net as it contains more information.)

**Comment by Sophietn** [comment]
Please can we add this copy to the adopters.md. 

We're sharing adopters of the Carbon Aware SDK with public evidence, although we know many others are also using the Carbon Aware SDK to reduce the carbon footprint their software. 

If you're using the Carbon Aware SDK and can share evidence, we'd love to add you to this list. Please reach out to carbon-aware-sdk@greensoftware.foundation.

**Comment by Sophietn** [comment]
Yes good idea, we'd be happy to accept additions via PRs too. 
Please add in your suggestion too - thanks!

**Comment by tkuramoto33** [comment]
Thank you!
I have updated my PR.

**Comment by Sophietn** [comment]
LGTM I've added a comment
