### ISSUE TITLE
Update documentation of secureness (security.md)

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#415]
Need to showcase that we match the applicable criteria for the Open SSF Best Practice Badge

**Comment by Willmish** [comment]
https://www.bestpractices.dev/en
https://github.com/coreinfrastructure/best-practices-badge

Example minimal file: https://github.com/ossf/scorecard/blob/main/SECURITY.md
https://github.com/ossf/scorecard/tree/main

**Comment by Willmish** [comment]
Cannot provide an SRA - include that the team will reply as soon as possible

its logging the location of the requested location - purpose of SDK hence acceptable - https://github.com/Green-Software-Foundation/carbon-aware-sdk/security/code-scanning?query=is%3Aopen+branch%3Adev+severity%3Amedium

**Comment by Sophietn** [comment]
@Willmish when do you think you'll have this one ready by?

**Comment by Sophietn** [comment]
Hey @Willmish any update on this one ahead of Graduation aim date tomorrow?

**Comment by Willmish** [comment]
Hi @Sophietn , PR now open : #464
