### ISSUE TITLE
Add disclaimer banner to any public-facing documentation (docusaurus webpage)

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#416]
Banner disclaimer wording:

[!important] Incubation Project This project is an incubation project being run inside the Green Software Foundation; as such, we *DON’T recommend using it in any critical use case. Incubation projects are experimental, offer no support guarantee, have minimal governance and process, and may be retired at any moment. This project may one day graduate, in which case this disclaimer will be removed.

**Comment by danuw** [comment]
Example banner given by @Sophietn  currently visible at https://if.greensoftware.foundation/



![Image](https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/8134789/733252b4-b1a3-40c9-aac8-1b96a2daac47)

**Comment by Sophietn** [comment]
Here's the PR for adding it to the IF document website, in the IF-docs repo https://github.com/Green-Software-Foundation/if-docs/pull/11

**Comment by danuw** [comment]
trying to use https://docusaurus.io/docs/api/themes/configuration#announcement-bar - adding link for reference

**Comment by danuw** [comment]
@Sophietn can you [double check](https://green-software-foundation.github.io/carbon-aware-sdk/) - should look something like below. 

> Please note, using out of the box announcement bar, so disclaimer can be closed and should only reappear on the same browser when we increment the announcement id.

<img width="1013" alt="medium size screen" src="https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/8134789/4e1b6fa8-8c77-49d9-91de-dafc3d43e6d9">
<img width="1673" alt="big size screen" src="https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/8134789/cff33bf6-1560-4e2e-a66b-be86aa1435ef">
<img width="547" alt="small size/mobile size screen" src="https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/8134789/666d41ed-558a-45ef-b6a3-39fb1adfa915">

**Comment by danuw** [comment]
I have since bolded the message

<img width="1673" alt="big size screen bold message" src="https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/8134789/40856573-bfec-4fc2-bd50-5a4a40ca93b0">

**Comment by Sophietn** [comment]
LGTM thank you

**Comment by Sophietn** [comment]
Happy to close this issue  @danuw ?
