### ISSUE TITLE
Create release notes for 1.2

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#434]
Create a PR with updated change log.

I will be using PRs listed here to start https://github.com/Green-Software-Foundation/carbon-aware-sdk/pulls?q=is%3Apr+label%3Av1.2+is%3Aclosed

I will need support to ensure nothing was missed from the issues too... (start here - currently can only see one bug I will list too https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues?q=is%3Aissue+label%3Av1.2+is%3Aclosed)

Please feel free to add anything missing in the comments...

**Comment by Sophietn** [comment]
@danuw do we have an update ahead of the weekly call tomorrow? 
It'd be great to know a new v1.2 release date
@Willmish @vaughanknight
