### ISSUE TITLE
[Bug]: Code coverage: Main release check issues to review

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#438]
### What happened?

There were issues with codecov action in main that was not spotted in dev.

We need to review the issues and understand the context

https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/437/checks?check_run_id=19776495409

### client

WebAPI (Default)

### Relevant log output

```shell
https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/437/checks?check_run_id=19776495409
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YaSuenag** [comment]
@vaughanknight CC: @Sophietn 
Do you have any updates for this issue?
Sorry to be pushy on this, but we are worried with the year's end break that it will not be wrap up in time, as we depend on this for some work be closed this year...

**Comment by nttDamien** [comment]
@danuw Is there anything we can do to help speed up the process for this ?

**Comment by Sophietn** [comment]
Hi @YaSuenag @nttDamien just so you know I chased @danuw @vaughanknight and @Willmish on email on 20/12. Still awaiting their reply. 
It's now looking unlikely v1.2 will be before new year. 
Next meeting is 9th Jan, but we are hoping for an async release from @vaughanknight before then

**Comment by YaSuenag** [comment]
CodeCov reports that the following files are not covered by the test:

* src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMapsFree/src/ElectricityMapsFreeDataSource.cs
* src/CarbonAware.WebApi/src/Models/CarbonIntensityDTO.cs
* src/CarbonAware.WebApi/src/Controllers/CarbonAwareController.cs
* src/CarbonAware.DataSources/CarbonAware.DataSources.ElectricityMaps/src/ElectricityMapsDataSource.cs

I guess they happened on following PRs:

* https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/294/checks
* https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/365/checks
* https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/389/checks

I pasted link of "Checks" tab, then we cannot see CodeCov result in them curiously, on the other hand we can see the result of CodeCov from PR of v1.2 integration (#437) - number of checks is diffent: #437 checks 15 items, the others check 9, they do not include CodeCov. So I guess some configuration is different between `dev` and `main` (but I'm not sure).

Anyway, total coverage (project) has been passed by CodeCov, so I think the error in patch check is not so important (it is better to pass of course).

**Comment by danuw** [comment]
Codecov was added to the repository as an application (we believe as a side effect of https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/429

Upon investigation codeconv only started on the repo from the 27th of Nov and only applies to carbon-aware-sdk

![Code coverage only applies to carbon-aware-sdk repo](https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/8134789/ab910791-09ea-4d32-abb7-1dd7214d85be)
![Codecov was enabled on the ](https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/8134789/b9d94ec4-7694-455c-b927-f2158ede34f1)

Going forward, we would like to restore codecov not being a requirements for releases, and maybe reinstate it if and when needed...

**Comment by nttDamien** [comment]
Thanks a lot for all the actions, does it mean v1.2 will be release this week ?
________________________________

**Comment by Sophietn** [comment]
Hopefully! 
@vaughanknight @Willmish @danuw - can we merge the PR?

**Comment by nttDamien** [comment]
[like]  RDH ＲＯＵＸ Ｄａｍｉｅｎ/Roux, Damien (... reacted to your message:
________________________________

**Comment by danuw** [comment]
we closed this - we are now tracking further open actions with #438
