### ISSUE TITLE
[Bug]: lack of Linux support

### ISSUE THREAD

**Issue by mkbane** [Green-Software-Foundation/carbon-aware-sdk#439]
### Contact Details

m.bane@mmu.ac.uk

### What happened?

As far as I can tell from the README files, Windows and Mac are supported but not Linux. Can you clarify if this is true (and why?), or add relevant instructions within the README files. Many thanks, M

### client

CLI

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danuw** [comment]
Hi @mkbane, Linux should be supported too (the tools we use are cross platform). Have a you had a chance to test and confirm? Could confirm in particular if you encountered any problems please?

cc @Willmish @vaughanknight

**Comment by danuw** [comment]
Hi @mkbane will close this issue in a week if I don't hear back, assuming this cannot be reproduced.

Let us know

**Comment by Willmish** [comment]
@mkbane AFAIK, the instructions for Mac should work just as fine for Linux, SDK is written in .NET Core and can be cross built for Linux, MacOS and Windows the packages/docker images we distribute with each release (as well as development packages) are actually built for Linux: https://github.com/Green-Software-Foundation/carbon-aware-sdk/pkgs/container/carbon-aware-sdk/167877520?tag=latest

If you find any issues with building from scratch for Linux following the instructions, please point out where you identified them and share in a PR if you manage to fix them!

**Comment by danuw** [comment]
Closing for now as no news
