### ISSUE TITLE
[Feature Contribution]: Add support for WattTime v3 - latest version of the API with new features and coverage

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#443]
### What happened?

WattTime just released a new version of their API. 
https://watttime.org/data-science/release-notes/#:~:text=APIv3%20release

>We’re excited to announce the release of our upgraded API (version 3). This new API brings many improvements including more intuitive and descriptive data delivery, error handling, and more. We are publishing data for 12 new countries which are only available in the new API. In addition to CO2, in the new API we also offer our Health Damage data signal which estimates the damage to human life and health caused by pollution from power plants. Our new [coverage map](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.watttime.org%2Fdocs-dev%2Fcoverage-map&data=05%7C02%7Cdan.benitah%40avanade.com%7Cdd087b75865f42f5bc1d08dc0e18e575%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C638400748049569688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C41000%7C%7C%7C&sdata=plJqjELmrlvIbQ7amlaePdvD%2BDnlfJxZvb5Gj5ruRqg%3D&reserved=0) shows the new countries we cover and where we offer each of our data signals.

This change needs to happen before June 2024 at which point the current version of the API will be out of service.

>Transition Resources: We want this transition to be as easy as possible and worth the effort to upgrade. We’ve prepared a number of resources to guide you through the transition and help you get acquainted with the new API, new regions, and new signals. 
[Transition Guide for APIv2 -> APIv3](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.watttime.org%2F%23tag%2FTransitioning-from-APIv2-to-APIv3&data=05%7C02%7Cdan.benitah%40avanade.com%7Cdd087b75865f42f5bc1d08dc0e18e575%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C638400748049569688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C41000%7C%7C%7C&sdata=XXT8gPS8lMbdbHz4T7zSKkrSkQyO0PUrlRiz4WsVZmE%3D&reserved=0)
[APIv3 documentation](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.watttime.org%2F&data=05%7C02%7Cdan.benitah%40avanade.com%7Cdd087b75865f42f5bc1d08dc0e18e575%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C638400748049569688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C41000%7C%7C%7C&sdata=9Z1dAkE5dV1XYiYISu8PIHDH7owN5pk37BgFaxoA6Ok%3D&reserved=0)
[Release notes](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.watttime.org%2Fdata-science%2Frelease-notes%2F&data=05%7C02%7Cdan.benitah%40avanade.com%7Cdd087b75865f42f5bc1d08dc0e18e575%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C638400748049569688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C41000%7C%7C%7C&sdata=a%2FiChmieUTrxYuraZZqWd4R6ZbxC9HRsN%2FXHXZAPmGQ%3D&reserved=0) related to the API, Data models, and Methodology
[Data Signals Overview](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwatttime.org%2Fdata-science%2Fdata-signals%2F&data=05%7C02%7Cdan.benitah%40avanade.com%7Cdd087b75865f42f5bc1d08dc0e18e575%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C638400748049569688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C41000%7C%7C%7C&sdata=g0xHXXtbBMwGxS5lOd8jiYjVFRTJABZSy%2BxO%2Buc6eek%3D&reserved=0) to explain each of the data types we offer
[Methodology & Validation](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.watttime.org%2Fdata-science%2Fmethodology-validation%2F&data=05%7C02%7Cdan.benitah%40avanade.com%7Cdd087b75865f42f5bc1d08dc0e18e575%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C638400748049569688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C41000%7C%7C%7C&sdata=HKXNj8OCX0QR%2F%2BXyU8S%2Bek4Sm6DG0oLrxwwlVtsen%2Fs%3D&reserved=0) has been updated and expanded

>Additional Support: WattTime will host a Q&A webinar about the new API and new features on Tuesday, January 23, 2024 at 11:30AM US-Pacific / 2:30PM US-Eastern. [Webinar details and sign-up are here](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapp.livestorm.co%2Fwatttime%2Fwatttime-new-api-features-and-overview&data=05%7C02%7Cdan.benitah%40avanade.com%7Cdd087b75865f42f5bc1d08dc0e18e575%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C638400748049569688%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C41000%7C%7C%7C&sdata=4fV%2BK1O%2Bt%2F0T4qbqSUYxAH4S%2BLX%2FlMuHaY%2F300Cm8r8%3D&reserved=0), and if you miss the webinar the recording will be accessible on-demand using the same page after the event concludes.

TODO:
- [ ] Gap Analysis
- [ ] Create migration backlog

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by Sophietn** [comment]
**Actions** 

- [ ] Identify what APIs we currently call 
- [ ] Identify what's changed (response codes?)
- [ ] Document what we believe
- [ ] Confirm with Watttime the work we've identified that needs to be done 

NTT DATA don't feel like they have clear enough awareness to do this work.

**Comment by danuw** [comment]
@vaughanknight documented the changes here https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/wattime-v3-support/casdk-docs/docs/architecture/decisions/0016-watt-time-v3.md

**Comment by danuw** [comment]
Done as part of #532
