### ISSUE TITLE
Update the Carbon Aware SDK docusaurus link

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#467]
**What:** Fix a domain link issue
**Why:** So this project's docusaurus link follows the link structure of the IF one https://if.greensoftware.foundation/

**To do:**

The Carbon Aware SDK docusaurus is currently found at https://green-software-foundation.github.io/carbon-aware-sdk/

@osamajandali Please can this link be updated to https://carbon-aware-sdk.greensoftware.foundation/

**Comment by osamajandali** [comment]
Done!

**Comment by Sophietn** [comment]
Thank you! @osamajandali

**Comment by Sophietn** [comment]
fyi @danuw @vaughanknight @Willmish 
Docusaurus is now found at https://carbon-aware-sdk.greensoftware.foundation
