### ISSUE TITLE
[Feature Contribution]: Update contribution documentation to include examples of areas of contribution opportunity

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#479]
### What happened?

The contribution documentation needs to to include examples of areas of contribution opportunity to give a bit more clarity, just one sentence per item.  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by danuw** [comment]
Changes have been merged for closing
