### ISSUE TITLE
Release 1.3 - Graduation Release 

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#483]
### What happened?

This is for the graduation release for the CarbonAware SDK 1.3 version.  All details will be in the PR contents, including issues, bugs, and upstream PR's.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by danuw** [comment]
Will close. 

Release can be found here : https://github.com/Green-Software-Foundation/carbon-aware-sdk/releases/tag/v1.3.0
