### ISSUE TITLE
[Bug]: Getting started guide is lost

### ISSUE THREAD

**Issue by PatrickBichiou** [Green-Software-Foundation/carbon-aware-sdk#487]
### Contact Details

pbichiou@logic.tv

### What happened?

Getting started guide is not longer available: https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/overview.md (404)

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danuw** [comment]
Hi @PatrickBichiou , documentation has moved one level down into the casda-docs folder.
https://github.com/Green-Software-Foundation/carbon-aware-sdk/tree/dev/casdk-docs/docs

You also have the ability to access the documentation through the new web interface https://carbon-aware-sdk.greensoftware.foundation/

The 2 main page you would be interested in your case are:
- https://carbon-aware-sdk.greensoftware.foundation/docs/quickstart
- https://carbon-aware-sdk.greensoftware.foundation/docs/overview/enablement

Was there anything else you were after?

**Comment by PatrickBichiou** [comment]
Thank you for the fast and helpful answer

**Comment by danuw** [comment]
Pleasure - anything else I can help with or happy for me to close this?

**Comment by PatrickBichiou** [comment]
Thanks - can be closed.
