### ISSUE TITLE
🎯 2024-04-23 Carbon Aware SDK Weekly Meeting 

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#504]
## Date
2024-04-23 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes

- v1.4 release 
**We shouldn't release until this v1.4 release also adheres to all [Graduation criteria quality](https://oc.greensoftware.foundation/project-lifecycle.html#graduated).**
        - Does our documentation eg. README need updating? README doesn't need updating (we need to check what's in the current documentation and see if we need to update anything eg. mentions of .NET7)
        - @vaughanknight has checked in with @danuw re. release notes. Vaughan will create them if Dan's absent. 
        - Target release date = unable to set it now.  But aiming for within the next 2 weeks. 

- .NET8 article #501 
Beginning of May holiday in Japan - likely to have a draft together mid May. Blocked by v1.4 release, and publishing new Helm chart. 

- IF PlugIn #502 - updated a couple of the points on the issue. 

- Watt time v3
In June the current version will no longer be supported. We need to 
       - update the end points so the end points are connected to v3 and 
       - ensure the new functionality in v3 works for our SDK.
       Tracked in #443 
**We'll do this implementation straight after the v1.4 release as a priority, but we can start the analysis beforehand** 
https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/443#issuecomment-2071633432 

# PRs
#500  - Not dependent on .NET8, doesn't need to be in the .NET8 branch. Could be merged now
But .NET8 release is dependent on this. @vaughanknight submitted review and merged. 
We'll use this in the github workflow of the v1.4 release. 

# Issues 
#445 - spoke about bringing codecov back as our security.md mentions we use it. 

## Discussion 
- [ ]  

## Action Items
- [x] @Sophietn update CA SDK confluence page to replace incubation banner - #505 
- [x] @Sophietn create issue to check / review documentation referencing .NET7 and complete this work. 

**Meeting attended by**

**Comment by nttDamien** [comment]
attended

**Comment by Sophietn** [comment]
Attended

**Comment by vaughanknight** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by vaughanknight** [comment]
Just a note that the URL strings for the API are in the querystrings.cs file, in the constants directory, alongside paths etc.  i.e. 

```
    public const string Data = "data";
    public const string Forecast = "forecast";
    public const string BalancingAuthorityFromLocation = "ba-from-loc";
    public const string Login = "login";
    public const string Historical = "historical";
```

**Comment by Sophietn** [comment]
@vaughanknight @danuw
I have reviewed all our documentation in issue #506 
Enablement & security both reference .NET6 so these will definitely need updating.
