### ISSUE TITLE
[Bug]: Project Page wiki from GSF website still says it's in incubation

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#505]
### What happened?

Browse to https://greensoftwarefoundation.atlassian.net/wiki/spaces/~612dd45e45cd76006a84071a/pages/17137665/Opensource+Carbon+Aware+SDK ... the website still says the project is in incubation and needs updating.  Has been discussed on the CA SDK weekly call.

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sophietn** [comment]
I've completed this - now the Confluence page lists the Graduated banner
