### ISSUE TITLE
2024-04-30 Carbon Aware SDK Weekly Meeting 🎯

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#507]
## Date
2024-04-30 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes

- v1.4 release 
**We shouldn't release until this v1.4 release also adheres to all [Graduation criteria quality](https://oc.greensoftware.foundation/project-lifecycle.html#graduated).**
        - #506 
        - security.md and enablement.md definitely need updating 
        - Release notes - we've been waiting on @danuw who is on holiday. @vaughanknight will ask him again. But it's most likely we will release once he is back from holiday. 

- .NET8 article #501 
Beginning of May holiday in Japan - likely to have a draft together mid May. Blocked by v1.4 release, and publishing new Helm chart. Aiming to share a draft with Vaughan end of next week / beginning of following week. Then GSF Comms will review before publishing. 

- IF PlugIn #502 
Waiting on @danuw to return before agreeing the decisions in the issue. 

- Watt time v3 #443 - What actions do we need to take?
Actions outlined in this comment:
https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/443#issuecomment-2071633432 

- [ ] Review Pull Requests
- [ ] Discuss Issues

# PRs

# Issues 
#445 - We should bring codecov back as our security.md mentions we use it. What actions do we need to take?
Comment on this issue here https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/445#issuecomment-2084578935

## Discussion 
- [ ]  

## Action Items
- [ ] @Sophietn create an issue to update enablement and security mds. 
- [x] @vaughanknight to ask Dan about release notes for v1.4 release. 
- [x] @vaughanknight create an issue for Gap analysis for watttime v3 upgrade. https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/510

## Next Meeting 
Tuesday 7th May @Sophietn is away on holiday. 

**Meeting attended by**

**Comment by vaughanknight** [comment]
Attended

**Comment by YaSuenag** [comment]
Attended

**Comment by Sophietn** [comment]
Attended

**Comment by nttDamien** [comment]
attended

**Comment by danuw** [comment]
I have created the changelog, and FYI I have also done a bit of clean up in branches (I only deleted branches that indicated having been merged or closed)
