### ISSUE TITLE
Case-study submission - Microsoft

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#508]
# Case Study Template

*This is a template to use for case studies that are submitted that leverage the Carbon Aware SDK. These case studies will be published to the Carbon Aware SDK repository*

> We will contact the person who created this issue to follow up prior to publishing any case studies for clarification and alignment

*Please delete the text in italics and replace it with the appropriate information.*

*For more information on any of the items, the final reference is the [SCI Specification](https://github.com/Green-Software-Foundation/software_carbon_intensity/blob/main/Software_Carbon_Intensity/Software_Carbon_Intensity_Specification.md)*

*If you find errors, or have further questions, please feel free to raise an [issue](https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues).*

## Overview

https://devblogs.microsoft.com/ise/saving-co2-using-location-and-time-shifting-in-azure/

## Describe the solution that implements the Carbon Aware SDK

_A textual description of the solution that implements the Carbon Aware SDK_

_A textual description of the action that is taken that reduces emissions due to leveraging the Carbon Aware SDK_

## Architecture for the solution (if applicable)

_An architecture diagram of the solution described in this use case_

### Technical details of the components in the architecture

_Textual description with technical details of each component provided in the architecture diagram_

## Carbon Aware SDK impact (both emissions impact and business impact)

_Textual description of the emissions impact and how it was measured_

_Textual description of the business impact beyond the emissions impact (if applicable)_

## Any public press release information that relates to the 

_Titles and links to press releases that can be viewed publicly online_ 
https://devblogs.microsoft.com/ise/saving-co2-using-location-and-time-shifting-in-azure/

## Any other notes of significance 

_For example_

_Was the SCI used?_

_Was this built in conjuction with another party that should be included in the case study?_

_Was there a contribution back to the Carbon Aware SDK project as part of this?_

_Are there any further plans to implement the Carbon Aware SDK across other solutions that can be discussed?_

_Are there any further plans to leverage other aspects of the Green Software Foundation to drive positive impact with software?_

**Comment by Sophietn** [comment]
@vaughanknight do you want to flesh the description of this issue out before we add Microsoft to our adopters.md?

**Comment by danuw** [comment]
@vaughanknight was there an action on you for this?
