### ISSUE TITLE
Gap Analysis for WattTime v3

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#510]
### What happened?

We need to create a gap analysis for WattTime v3 to support #443 

This includes:
- Minimum to support v3 release end of v2 support in June 
  - Data type changes or schema changes
  - Path changes and mapping 
  - Response codes 
  - Any regression
- Any future capabilities we may want to support 
  - Documentation of what these could be 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by Sophietn** [comment]
Linked issue https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/443

**Comment by danuw** [comment]
Can be closed 
cc #532
