### ISSUE TITLE
2024-05-07 Carbon Aware SDK Weekly Meeting 🎯

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#514]
## Date
2024-05-07 - 7am UTC

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
We're happy to start recording these meetings if we receive any requests to record them.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

| Full Name | Affiliation | GitHub username (optional) |
|---|---|---|
|Vaughan Knight | Microsoft |  [vaughanknight](https://github.com/vaughanknight) | 

Any untracked attendees will be added by the GSF team below

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Review the agenda and suggest new agenda points
- [x] Approve Past Meeting Minutes

  - [ ]  v1.4 release 
**We shouldn't release until this v1.4 release also adheres to all [Graduation criteria quality](https://oc.greensoftware.foundation/project-lifecycle.html#graduated).**
      - [ ] https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/506
      - security.md and enablement.md definitely need updating 
          - [ ] https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/512
          - [ ] Create issue / link to 512
      - [ ] Release notes - we've been waiting on @danuw who is on holiday. @vaughanknight will ask him again. But it's most likely we will release once he is back from holiday. https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/511

  - [x] .NET8 article #501 
Beginning of May holiday in Japan - likely to have a draft together mid May. Blocked by v1.4 release, and publishing new Helm chart. Aiming to share a draft with Vaughan end of next week / beginning of following week. Then GSF Comms will review before publishing. 
- expected this week/next week

  - [x] IF PlugIn #502 
Waiting on @danuw to return before agreeing the decisions in the issue. 

  - [x] Watt time v3 #443 - What actions do we need to take?
Actions outlined in this comment:
https://github.com/Green-Software-Foundation/carbon-aware-sdk/issues/443#issuecomment-2071633432 

- [ ] Review Pull Requests
- [ ] Discuss Issues

# PRs

# Issues 

## Discussion 
- [ ]  

## Action Items
- [ ] 

**Meeting attended by**

**Comment by vaughanknight** [comment]
Attended

**Comment by tiwatsuka** [comment]
Attended

**Comment by danuw** [comment]
- feature suggestion : named regions and multiple configurations - (ability to create more mapping configurations and sepcifying the mapping configuration in the request)
  - [ ] create issues for this
- [ ]

**Comment by YaSuenag** [comment]
Attended
