### ISSUE TITLE
[Bug]: Avoid inotify limit in WebAPI container on Kubernetes

### ISSUE THREAD

**Issue by YaSuenag** [Green-Software-Foundation/carbon-aware-sdk#528]
### What happened?

We are using WebAPI container on Kubernetes with Helm chart, then we saw a error which explained in following URL.
https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/?view=aspnetcore-8.0

We think it is better to set `DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE` environment variable as the article said because we cannot update appsettings.json - it is mounted as `subPath`.

In general, reload config might be useful if WebAPI runs on the OS (not coantainer). So I will modify Helm chart to add environment variables for WebAPI container if you agree. What do you think?

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vaughanknight** [comment]
@danuw - we discussed in the #530 meeting that this probably should be an ADR, as it can be done via code or configuration and it would be good to have the flexibility of both, with appsettings.json not having in flight updates being possible for production systems by default.

**Comment by YaSuenag** [comment]
Before proposing ADR, I'd like to sort out the solution.

According to [Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/?view=aspnetcore-8.0) and [discussion on GitHub](https://github.com/dotnet/AspNetCore.Docs/issues/19814), we have two approach for this issue:

1. Load JSON manually via [AddJsonFile](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.jsonconfigurationextensions.addjsonfile?view=net-8.0#microsoft-extensions-configuration-jsonconfigurationextensions-addjsonfile(microsoft-extensions-configuration-iconfigurationbuilder-microsoft-extensions-fileproviders-ifileprovider-system-string-system-boolean-system-boolean)) with `reloadOnChange: false`
2. Set `DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false` as an environment variable

We have following code in Program.cs:
https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/4f5dbd2f505b4d6dc14983bc5b4d60bd97c48210/src/CarbonAware.WebApi/src/Program.cs#L18
According to [Microsoft Learn](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-8.0#default-application-configuration-sources), `WebApplication.CreateBuilder()` loads appsettings.json implicitly, so we have no chance to apply 1 (`reloadOnChange: false`), thus we have to apply 2 (`DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE`).

Hence I think it is the best solution to set `DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE` if need, and I want to modify Helm Chart that the user can be add this environment variable if want. For Docker users, they just add `-e DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false` to their `docker run`.

@vaughanknight @danuw  What do you think?  
I will create PR for Helm Chart without ADR if you agree.

**Comment by YaSuenag** [comment]
Suggested fix: https://github.com/YaSuenag/carbon-aware-sdk/commit/d2ff48e96e3202ea537da627f652cca86945b555
