### ISSUE TITLE
[Bug]: 1-pr.yaml should upgrade actions/upload-artifact

### ISSUE THREAD

**Issue by YaSuenag** [Green-Software-Foundation/carbon-aware-sdk#564]
### What happened?

We saw following error on GHA workflow in 1-pr.yaml:

https://github.com/Green-Software-Foundation/carbon-aware-sdk/actions/runs/10898430589/job/30242068068?pr=562#logs
> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v1`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

actions/upload-artifact is used to upload swagger document as following. We need to upgrade, and also need to check whether same problem could be happen in other workflows (usage of upload-artifacts).

https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/93d9ba214bde4296c9476240a1c4b2a4e2bb37f3/.github/workflows/1-pr.yaml#L131

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danuw** [comment]
Closing as already sorted in dev
