### ISSUE TITLE
[Bug]: Discrepancy between main and dev leads to merge conflicts

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#584]
### What happened?

fix merge issues for https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/583

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YaSuenag** [comment]
I cannot rebase `dev` branch with `main` smoothly - it might be a hit of the problem, but I'm not sure.

As an option, merge v1.6.1 in `dev` into `main` with manually confliction resolution, then rebase `dev` for future release.

**Comment by danuw** [comment]
Good idea - will branch main and merge with dev. Will do as soon as possible. Thank you @YaSuenag

**Comment by YaSuenag** [comment]
@danuw 
Can you do rebase merge? It might succeed even if merge commit would fail in my experience.
