### ISSUE TITLE
[Feature Contribution]: WattTime Integration, Refactoring the WebAPI

### ISSUE THREAD

**Issue by KanishkT123** [Green-Software-Foundation/carbon-aware-sdk#59]
### What happened?

This feature contribution will add WattTime plugin support and various improvements to the Carbon Aware SDK WebAPI and CLI. The specific details have been discussed with UBS, GSF and Microsoft. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by vaughanknight** [comment]
Now merged and in dev.  Thanks all for their contributions 👍
