### ISSUE TITLE
Set Up Automated Build

### ISSUE THREAD

**Issue by vaughanknight** [Green-Software-Foundation/carbon-aware-sdk#6]
Set up github actions automated build agent

**Comment by yelghali** [comment]
Hello, I have submited a first iteration in [feat/build-ci branch](https://github.com/Green-Software-Foundation/carbon-aware-sdk/tree/feat/build-ci)

two [Github action workflows](https://github.com/Green-Software-Foundation/carbon-aware-sdk/actions):
* BUILD CLI in DOTNET: builds the dotnet projects + Runs Unit Tests & Regression Test (calling the Carbone Aware Cli for Sydney Location)
* Security Code Scan with CodeQL: the security alerts can be found in the [Security Tab](https://github.com/Green-Software-Foundation/carbon-aware-sdk/security)

We can discuss how to improve further in our next meeting. thank you
