### ISSUE TITLE
[Feature Contribution]: Further WattTime Integration, with Forcasting, and first Integration Tests

### ISSUE THREAD

**Issue by dnastrain** [Green-Software-Foundation/carbon-aware-sdk#63]
### What happened?

This feature contribution will add further [WattTime](https://www.watttime.org/api-documentation/) plugin support, including Forcasting. 
Adding first versions of Integration Tests for both JSON and WattTime plugins (aka dataSources), using [WireMock](https://github.com/WireMock-Net/WireMock.Net) for mocking WattTime.
Includes updates of file folders and structures to match dotNet standards. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by vaughanknight** [comment]
This is now merged into dev.  Closing out.  Thanks everyone for their contribution, amazing work 👍
