### ISSUE TITLE
[Bug]: Lack of important details in the getting started documentation

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#78]
### What happened?

The carbone-sdk/getting started md files is missing some key information to be able to run the cli (and likely the webapi) such as :
- [x] Pre-requisites
- [x]  how to set up a whattime account

### client

CLI

### Relevant log output

```shell
N/A
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Willmish** [comment]
To review again + add examples of usage for the CLI/ Web API in the Getting started doc.

**Comment by vaughanknight** [comment]
Dan to look at this Thursday morning.  If anyone else would like to look at this prior let Dan know here.

**Comment by vaughanknight** [comment]
@danuw to look a bit more for anything missing.

**Comment by vaughanknight** [comment]
Updates to folder structure as per #105 and README.md updated to be clear and obvious overview.
* Folder structure to be updated @danuw 
* README.md to be updated by @vaughanknight

**Comment by vaughanknight** [comment]
We discusssed README in the root, move all other non-project related documents into docs.  if possible also move projects for 1.0 but not critical.

**Comment by danuw** [comment]
This was closed in error and still requires small doc adjustments before Release 1.0

**Comment by danuw** [comment]
This will now be closed - follow ups workitem on #112
