### ISSUE TITLE
[Bug]: Too much data generated by default when polling `/emissions/bylocation` endpoint

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/carbon-aware-sdk#83]
### Contact Details

GitHub/Slack: Willmish

### What happened?

- When calling GET on the `/emissions/bylocation` endpoint, and only providing Location and not a time frame, by default the SDK requests data for a 7 days in 5 minute intervals (hundreds of data).
- When calling the endpoints with the same `time` and `toTime` , SDK will respond with 2 values: before `time` and after `toTime`

This doesn't seem like a healthy default for the SDK.

Instead, I suggest:
- [ ] the SDK by default asks for 20-50 data points in 5 minute intervals, going from most recent to a few hours before current time.
- [ ] SDK should not give values after `toTime`, only up to - this way we will also receive a single value when `time` is the same as `toTime`

Example Swagger UI query which produces a lot of data:
<img width="1423" alt="Screenshot 2022-07-27 at 16 33 52" src="https://user-images.githubusercontent.com/26546660/181288576-371606a0-055c-46f6-9ff3-32b7b8cba6b1.png">

### client

WebAPI (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danuw** [comment]
Great @Willmish ... Even 50 would be too much. If people can override default value to choose I would limit to 20... Hard to digest otherwise.

**Comment by NickVilimek** [comment]
Do we want to include this parameterization for just the webapi or also for the CLI client as well?

**Comment by danuw** [comment]
@NickVilimek , CLI as well please (assuming it is mainly around passing same params and defaults to underlying common methods)

**Comment by NickVilimek** [comment]
@danuw sure. 

Are we worried about confusing users who pass it timeframes? If users are unaware of the 20 item limit, they could be confused when asking for a 2 PM CST - 5 PM CST timeframe for example because it'd only return 20 items * 5 minute intervals = 100 minutes to 2 PM - 3:40 PM. I could see them wondering why it only returned a subset of the results they asked for.  

In my head, I see this as a pagination feature. One way to implement is to have have --pageSize to override the 20 item limit and --pageNumber to page through more than the first 20 results. This could also include a --no-paginate flag to return everything.

The alternative could be to return everything by default, but apply the pagination via --pageSize and --pageNumber if they are passed. This could help avoid confusion for the scenario above and anyone who in unaware of the item limit. 

Not sure if you have thoughts on this.

**Comment by Willmish** [comment]
> Are we worried about confusing users who pass it timeframes? If users are unaware of the 20 item limit, they could be confused when asking for a 2 PM CST - 5 PM CST timeframe for example because it'd only return 20 items * 5 minute intervals = 100 minutes to 2 PM - 3:40 PM. I could see them wondering why it only returned a subset of the results they asked for.

@NickVilimek , This looks like one viable option, although what I had in mind was simply change the default value to 20 items, but if user gives a timeframe which includes more than 20 elements, let him - worst case WattTime will throttle his request if it is truly huge.

Adding pagination parameters is an interesting approach to tackle this when data queries get *very* long, but not sure if I would rather just have a smaller default limit, which is disregarded when `time` and `toTime` parameters are present.

The amount of data could also be decreased by specifying the `duration` parameter, though I think it is not implemented at the moment? @vaughanknight might be able to confirm this.

What do you think about the pagination approach @vaughanknight ?

**Comment by danuw** [comment]
Hi @NickVilimek sorry for the delay.

I agree with you that if someone provides a start AND end time, then it should calculate and override the default limit.

My thoughts were (especially for new people using this) not to be overwhelmed by results. So I would have expected that we could have some default values:
- no start time => defaults to now
- no end time => stops when results limit is reached
- pagesize or nbResults (as no page really) => 20 (use -1 or less than zero for no limit? so it is clear when it has been overridden)
- location => I expect is the only required parameter or would we want to default this too?

So for example for different scenarios (with at least location):
- provide start time only => defaults nb of results or end time from nb of results
- provide start and end time => override nb of results to match start and end time requested
- provide nothing more => 20 first result for given location from now
- provide 50 for nb of results => 50 first results for given location from now

@NickVilimek does that make sense, and would that be ok? ( I believe the default value of less than zero is important to ensure we can do this as low level as possible so it applies across CLI and WebAPI, no?)

Let me know if above is not clear enough or misses key scenarios...

**Comment by danuw** [comment]
sorry did not respond to paging, but it may be good addition to have pagination, given how many results come back in case someone is using a UI, but I would not paginate by default

**Comment by danuw** [comment]
also forgot about the interval - updating above ...

**Comment by NickVilimek** [comment]
@danuw @Willmish Sounds good. I'm thinking interval can be opened as another feature is that will involve some standardization across providers. Dumb question, what does the "nb" stand for in "nbResults"? 

Also, location is already required. Also, if you don't provide start/end date, then end defaults to UTC now and start defaults to 7 days previous to UTC now so we are covered already there.

Just to clarify scenarios
1. "-l eastus" => return default 20 nbResults
2. "-l eastus -t 2022-08-12 --toTime 2022-08-19" => return all results and ignore nbResults
3. "-l eastus -t 2022-08-12" or "-l eastus --toTime 2022-08-19" => return default 20 nbResults
4. "-l eastus --nbResults 50" => return 50 results
5. "-l eastus --nbResults -1" => return everything

And same will apply to the web API as well of course.

**Comment by danuw** [comment]
Sounds great. Thanks @NickVilimek 

(Do we need to involve interval as an optional setting too?)

My bad for NB as I meant it as number. NbResults standing for number of results to return. Hope that makes sense and sorry for not making that clearer earlier.

**Comment by vaughanknight** [comment]
This may result to the 7 day windows when giving just "time" and no "toTime".  Need to investigate as bug for v1.0.

**Comment by vaughanknight** [comment]
We should look at the "time' and not "toTime" bug prior to pagination.   Is this raised as a bug?  I'll check.

**Comment by vaughanknight** [comment]
If giving a single time and no toTime the response should only give 1 result (most recent time prior to the `time` provided).  _Not_ the nearest time (which may be in the future).  Must be most recent prior.

**Comment by Willmish** [comment]
Found the culprit of 7 day default: https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/50303baff3dfaa4669c3b4f7a3110780f42f85ee/src/CarbonAware.Aggregators/src/CarbonAware/CarbonAwareAggregator.cs#L34

**Comment by danuw** [comment]
Do we feel we are clear on the scope of this bug towards release 1.0 and do we have an ETA for this please? 
cc @NickVilimek

**Comment by NickVilimek** [comment]
@danuw I think following this most recent plan above gives us everything we need. I'll start looking at this Sunday maybe. Hoping to be making a pull request early next week. Does that align with the v1.0 timeline?

**Comment by danuw** [comment]
I think so thanks very much

**Comment by danuw** [comment]
Hi @NickVilimek, any news please? Feel free to IM on slack or Teams during your hours so we can progress

**Comment by vaughanknight** [comment]
Would be great to get people to test this, so any assistance appreciated.

**Comment by vaughanknight** [comment]
Closed and merged.
