### ISSUE TITLE
[Feature Contribution]: Further WattTime Integration including Batch Historical Forecast, Batch Multi-Day Historical Actuals, Batch Avg Carbon Intensity and bug fixes

### ISSUE THREAD

**Issue by JenMadiedo** [Green-Software-Foundation/carbon-aware-sdk#87]
### What happened?

This feature contribution will add further [WattTime](https://www.watttime.org/api-documentation/) data source support, including endpoints for batch historical forecast, batch historical multi-day actuals, and batch average carbon intensity.

Also added updates to readmes and docstrings to better reflect endpoints and various use cases. Includes a handful of bug fixes such as improving defaulting/validation logic, the rolling average code, and adding support for app insights instrumentation key.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by Willmish** [comment]
Closed in https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/88 .
