### ISSUE TITLE
[Feature Contribution]: Local settings file as non tracked changes

### ISSUE THREAD

**Issue by danuw** [Green-Software-Foundation/carbon-aware-sdk#93]
### What happened?

_**As a** user of the SDK
**I want to** easily set my local settings
**So that** I can get started quickly and still be able to get latest without any conflict_

Local settings file as non tracked changes.
This should allow setting up the local machine without creating local changes and pull latest easily.

The local settings file would be called appsettings.local.json and be added to the .gitignore .
A template file would be added with placeholder for all settings needed. 
User would just have to copy and rename the file and update the value.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Feature Commitment

- [X] I commit to contributing this feature as a PR and working with the GSF to merge this feature into the Carbon Aware SDK.

**Comment by danuw** [comment]
I have some changes locally for this for the WebApi. Should have a PR for tomorrow.

**Comment by vaughanknight** [comment]
Local json file overrides all settings - something highlighted by @danuw that we need to capture in documentation just so developers understand the behaviours (and don't see it as a bug).

**Comment by vaughanknight** [comment]
Merged and closing.
